var annotationData = [
  {
    "id": "q_politics_20251231_044_55cd5793",
    "title": "Will any new countries be admitted to NATO in 2025?",
    "question_type": "binary",
    "options": [
      "Yes",
      "No"
    ],
    "background": "The expansion of NATO is a significant geopolitical event.",
    "resolution_criteria": "The question will resolve to YES if any new country officially becomes a member of the North Atlantic Treaty Organization (NATO) in 2025. Otherwise, it will resolve to NO.",
    "outcome": "False",
    "explanation": "\n## Executive Summary\nIn 2025, no new countries were admitted to the North Atlantic Treaty Organization (NATO). The primary driver for this outcome was a strategic pivot within the alliance to consolidate existing commitments and prioritize defense spending and internal readiness over expansion. The most prominent candidate, Ukraine, formally dropped its goal of NATO membership as part of ongoing peace negotiations to end the war with Russia. Other candidate countries, such as Georgia and Bosnia and Herzegovina, saw their prospects stall due to internal political complexities and a lack of consensus among existing NATO members for further enlargement during a period of intense global instability.\n\n## Timeline Of Key Events\n- **March 20, 2025:** Major NATO exercises led by British troops commence in Eastern Europe, reflecting the alliance's focus on readiness rather than expansion [art_politics_20250320_018_31888182].\n- **June 15, 2025:** The 2025 NATO Summit concludes. The alliance agrees to an ambitious defense spending expansion and internal strengthening. Enlargement discussions are notably sidelined [art_politics_20250615_002_513cd1aa, art_politics_20250615_003_df0e2120].\n- **June 15, 2025:** Reports emerge indicating Ukraine is willing to drop its ambitions to join NATO in exchange for progress in peace talks [art_politics_20250615_014_4bdfef47, art_politics_20250615_015_8b4ee1d1].\n- **October 5, 2025:** Hopes for NATO membership for Bosnia and Georgia are explicitly dashed for the year 2025 [art_politics_20251005_003_fad7f01a].\n- **December 15, 2025:** Ukraine formally drops its NATO bid as a condition of a broader peace settlement framework [art_politics_20251215_002_ec1b1d0a].\n- **December 31, 2025:** The year concludes with official confirmation that no new members were admitted to NATO in 2025 [art_politics_20251231_004_acd70532].\n\n## Causal Chain Analysis\nThe lack of NATO expansion in 2025 was caused by a combination of strategic reprioritization and shifting geopolitical realities. The root cause was the prolonged war in Ukraine and the resulting strain on the alliance's resources. This led to an intermediate mechanism where NATO leadership determined that the priority must be internal consolidation and boosting defense production, as formalized at the June 2025 summit [art_politics_20250615_002_513cd1aa]. Consequently, a proximate trigger for the non-expansion was Ukraine's strategic decision to leverage its NATO aspirations as a bargaining chip, eventually dropping its membership goal to facilitate peace negotiations [art_politics_20251215_002_ec1b1d0a]. This, combined with the lack of momentum for other candidates like Georgia and Bosnia [art_politics_20251005_003_fad7f01a], resulted in the final outcome of zero new admissions.\n\n## Countervailing Factors\nThe main force pushing toward expansion was the continued desire from candidate nations for security guarantees against Russian aggression. Notably, Polish President Duda and other Eastern flank members advocated strongly for offering an invitation to Ukraine [art_politics_20250615_017_ca1a4b01]. However, this push was overwhelmed by the pragmatic reality of peace negotiations, which required concessions on the membership issue, and hesitation from key members like the US and Germany to escalate tensions by formalizing an invitation while the conflict was active.\n\n## Event Candidate Inventory\n- **E1**\n  - title: NATO agrees to defense spending expansion at 2025 Summit.\n  - date: 2025-06-15\n  - why it matters causally: Signals the pivot toward internal readiness over enlargement.\n  - source article IDs: [art_politics_20250615_002_513cd1aa]\n- **E2**\n  - title: Ukraine drops NATO goal amid peace talks.\n  - date: 2025-12-15\n  - why it matters causally: Removes the most prominent candidate from consideration, ensuring no expansion.\n  - source article IDs: [art_politics_20251215_002_ec1b1d0a]\n- **E3**\n  - title: Bosnia and Georgia NATO hopes dashed.\n  - date: 2025-10-05\n  - why it matters causally: Confirms that secondary candidates will not be admitted in 2025.\n  - source article IDs: [art_politics_20251005_003_fad7f01a]\n\n## Evidence Mapping Table\n| Claim/Event | Article IDs | Date Support | Confidence (0-1) | Notes |\n|---|---|---|---|---|\n| NATO Summit focuses on internal spending, not expansion | [art_politics_20250615_002_513cd1aa] | 2025-06-15 | 0.9 | Summit results explicitly state priorities. |\n| Ukraine drops NATO ambitions | [art_politics_20251215_002_ec1b1d0a] | 2025-12-15 | 0.95 | Key concession in peace process. |\n| Bosnia/Georgia stalled | [art_politics_20251005_003_fad7f01a] | 2025-10-05 | 0.9 | No progress for other candidates. |\n| No members admitted in 2025 | [art_politics_20251231_004_acd70532] | 2025-12-31 | 1.0 | Definitive end-of-year review. |\n\n## Uncertainties And Alternative Paths\nThe primary alternative path would have been a rapid collapse of Russian forces, which might have opened a window for immediate Ukrainian accession. However, this did not materialize. There remains uncertainty regarding the long-term security architecture for Ukraine post-war, as the alternative arrangements (e.g., bilateral guarantees) have yet to be fully defined and tested.\n",
    "is_polymarket": false,
    "is_overlap": true,
    "market_open": "2025-01-01T00:00:00+00:00",
    "market_open_estimated": false,
    "market_close": "2025-12-31T23:59:59+00:00",
    "polymarket_url": null,
    "price_data": null,
    "events": [
      {
        "id": "evt_politics_20250320_001_347e86bf",
        "date": "2025-03-20 00:00",
        "title": "Major NATO exercises commence in Eastern Europe",
        "description": "Major NATO exercises led by British troops commence in Eastern Europe, reflecting the alliance's focus on readiness.",
        "impact": "**Affects:** No - Will any new countries be admitted to NATO in 2025  \n\n**Direction:** Towards outcome    \n\n**Reasoning:**\nFocus on readiness makes expansion less likely.",
        "has_impact": true,
        "in_market_window": false,
        "source_url": "https://www.gov.uk/government/news/thousands-of-british-troops-to-lead-major-nato-exercise-in-eastern-europe",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_politics_20250615_002_476223e6",
        "date": "2025-06-15 00:00",
        "title": "NATO agrees to defense spending expansion at 2025 Summit",
        "description": "The alliance agrees to an ambitious defense spending expansion and internal strengthening.",
        "impact": "**Affects:** No - Will any new countries be admitted to NATO in 2025  \n\n**Direction:** Towards outcome    \n\n**Reasoning:**\nFocus on internal spending makes expansion less likely.",
        "has_impact": true,
        "in_market_window": false,
        "source_url": "https://www.semafor.com/article/06/06/2025/nato-agrees-ambitious-defense-spending-expansion",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_politics_20250615_003_9578da25",
        "date": "2025-06-15 00:00",
        "title": "NATO sidelines enlargement discussions at 2025 Summit",
        "description": "Enlargement discussions are notably sidelined at the 2025 NATO Summit.",
        "impact": "**Affects:** No - Will any new countries be admitted to NATO in 2025  \n\n**Direction:** Towards outcome    \n\n**Reasoning:**\nSidelining enlargement makes expansion less likely.",
        "has_impact": true,
        "in_market_window": false,
        "source_url": "https://www.edrmagazine.eu/europe-insight-what-the-nato-summit-2025-means-for-eu-and-transatlantic-defense",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_politics_20250615_004_a404e0b7",
        "date": "2025-06-15 00:00",
        "title": "Polish President Duda advocates for offering an invitation to Ukraine",
        "description": "Polish President Duda and other Eastern flank members advocated strongly for offering an invitation to Ukraine.",
        "impact": "**Affects:** No - Will any new countries be admitted to NATO in 2025  \n\n**Direction:** Against outcome    \n\n**Reasoning:**\nAdvocacy for Ukraine makes expansion more likely.",
        "has_impact": true,
        "in_market_window": false,
        "source_url": "https://newsukraine.rbc.ua/news/nato-invitation-would-be-a-step-towards-real-1736956150.html",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_politics_20250615_005_47ce40d5",
        "date": "2025-06-15 00:00",
        "title": "Reports emerge indicating Ukraine is willing to drop its ambitions to join NATO",
        "description": "Reports emerge indicating Ukraine is willing to drop its ambitions to join NATO in exchange for progress in peace talks.",
        "impact": "**Affects:** No - Will any new countries be admitted to NATO in 2025  \n\n**Direction:** Towards outcome    \n\n**Reasoning:**\nWillingness to drop ambitions makes expansion less likely.",
        "has_impact": true,
        "in_market_window": false,
        "source_url": "https://www.cnbc.com/2025/12/14/ukraines-zelenskyy-ditches-ambition-to-join-nato-ahead-of-peace-talks.html",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_politics_20250615_009_bc489aea",
        "date": "2025-06-15 00:00",
        "title": "US and Germany hesitate to escalate tensions",
        "description": "Hesitation from key members like the US and Germany to escalate tensions by formalizing an invitation while the conflict was active.",
        "impact": "**Affects:** No - Will any new countries be admitted to NATO in 2025  \n\n**Direction:** Towards outcome    \n\n**Reasoning:**\nHesitation makes expansion less likely.",
        "has_impact": true,
        "in_market_window": false,
        "source_url": "https://www.semafor.com/article/06/06/2025/nato-agrees-ambitious-defense-spending-expansion",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_politics_20251215_007_00d70a4c",
        "date": "2025-12-15 00:00",
        "title": "Ukraine formally drops its NATO bid",
        "description": "Ukraine formally drops its NATO bid as a condition of a broader peace settlement framework.",
        "impact": "**Affects:** No - Will any new countries be admitted to NATO in 2025  \n\n**Direction:** Towards outcome    \n\n**Reasoning:**\nDropping bid makes expansion less likely.",
        "has_impact": true,
        "in_market_window": false,
        "source_url": "https://www.cnbc.com/2025/12/15/ukraine-gives-up-nato-bid-peace-talks.html",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_politics_20251215_010_2d105f97",
        "date": "2025-12-15 00:00",
        "title": "Peace negotiations require concessions on the membership issue",
        "description": "Peace negotiations required concessions on the membership issue.",
        "impact": "**Affects:** No - Will any new countries be admitted to NATO in 2025  \n\n**Direction:** Towards outcome    \n\n**Reasoning:**\nConcessions make expansion less likely.",
        "has_impact": true,
        "in_market_window": false,
        "source_url": "https://www.cnbc.com/2025/12/15/ukraine-gives-up-nato-bid-peace-talks.html",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_politics_20251231_008_b1651f99",
        "date": "2025-12-31 00:00",
        "title": "Official confirmation that no new members were admitted to NATO in 2025",
        "description": "The year concludes with official confirmation that no new members were admitted to NATO in 2025.",
        "impact": "**Affects:** No - Will any new countries be admitted to NATO in 2025  \n\n**Direction:** Towards outcome    \n\n**Reasoning:**\nOfficial confirmation makes expansion impossible.",
        "has_impact": true,
        "in_market_window": false,
        "source_url": "https://www.bbc.com/2025/12/31/nato-year-in-review-no-new-members.html",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      }
    ]
  },
  {
    "id": "q_sports_20260222_011_f522077b",
    "title": "Which country will win the most gold medals at the 2026 Winter Olympics in Milano Cortina?",
    "question_type": "mcq",
    "options": [
      "Norway",
      "Germany",
      "Canada",
      "United States"
    ],
    "background": "The 2026 Winter Olympics will be held in Milano Cortina, Italy. This question asks which nation will top the gold medal table, a prestigious achievement in international sports.",
    "resolution_criteria": "The question will resolve to the country that has won the most gold medals at the end of the 2026 Winter Olympics, as officially reported by the International Olympic Committee (IOC).",
    "outcome": "Norway",
    "explanation": "\n# Executive Summary\nNorway won the most gold medals at the 2026 Winter Olympics in Milano Cortina, setting a new single-Games record with 18 golds and 41 total medals. Their dominance was driven by unmatched performances in Nordic sports, specifically cross-country skiing, biathlon, and Nordic combined. Generational athletes like Johannes Hoesflot Klaebo and Jens Luras Oftebro executed flawless campaigns, sweeping multiple events and overwhelming the medal table. While nations like the United States performed exceptionally well in alpine, speedskating, and hockey, they could not match the sheer volume of Norway's victories in the endurance skiing disciplines.\n\n# Timeline Of Key Events\n- **2026-02-06 to 2026-02-21**: Johannes Hoesflot Klaebo wins six gold medals across cross-country skiing events, culminating in a historic victory in the men's 50km mass start, becoming the first Winter Olympian to win six golds at a single Games [art_sports_20260223_008_c20fc878].\n- **2026-02-20**: Johannes Dale-Skjevdal hits all 20 targets in the 15-kilometer mass start biathlon, securing Norway's 17th gold medal and breaking their previous Winter Olympics record [art_sports_20260222_007_ecbd4ab5].\n- **2026-02-21**: Klaebo's 50km cross-country mass start victory secures Norway's 18th gold medal [art_general_20260221_017_57fbdfe9].\n- **2026-02-22**: The United States wins the men's ice hockey gold against Canada, securing their 12th gold medal and finishing second overall, but well behind Norway's total [art_general_20260222_007_a44504a4].\n\n# Causal Chain Analysis\nThe outcome was **caused** by Norway's deep-rooted systemic advantages and talent pipeline in Nordic skiing disciplines. This structural focus **led to** the emergence of dominant individual athletes capable of sweeping multiple events. The presence of these generational talents, such as Johannes Hoesflot Klaebo and Jens Luras Oftebro, **resulted in** near-perfect execution during the Games; for instance, Oftebro went undefeated to win three golds in Nordic combined, while Klaebo captured six [art_sports_20260223_008_c20fc878]. These compounding individual successes **triggered** a rapid accumulation of medals, effectively mathematical elimination for other countries. Ultimately, Norway's dominance in events with numerous medal opportunities (cross-country and biathlon accounted for 25 medals) **resulted in** their final record-breaking tally of 18 gold medals.\n\n# Countervailing Factors\nThe United States mounted a strong challenge, putting together their best Winter Olympics performance in over two decades with 12 gold medals [art_sports_20260222_007_ecbd4ab5]. American athletes dominated in several areas, including Jordan Stolz winning three speedskating golds and Team USA capturing both men's and women's ice hockey titles [art_general_20260222_007_a44504a4]. However, this push was overwhelmed because the U.S. successes were spread across various disciplines, whereas Norway consolidated absolute dominance in sports that offered a high volume of medals, rendering the U.S. surge insufficient to contest the top spot.\n\n# Event Candidate Inventory\n- E1: Johannes Hoesflot Klaebo wins six gold medals, including the 50km mass start.\n  - Date: 2026-02-06 to 2026-02-21\n  - Causally matters: It contributed a massive one-third of Norway's total gold medal count, cementing their lead.\n  - Source: [art_sports_20260223_008_c20fc878], [art_general_20260221_017_57fbdfe9]\n- E2: Jens Luras Oftebro wins three gold medals in Nordic combined.\n  - Date: 2026-02-06 to 2026-02-21\n  - Causally matters: Undefeated sweep of the discipline added highly reliable golds to the Norwegian total.\n  - Source: [art_sports_20260223_008_c20fc878]\n- E3: Johannes Dale-Skjevdal wins the 15km mass start biathlon.\n  - Date: 2026-02-20\n  - Causally matters: It represented the record-breaking 17th gold medal for Norway, pushing them past their historical best.\n  - Source: [art_sports_20260222_007_ecbd4ab5]\n- E4: Team USA wins men's ice hockey gold.\n  - Date: 2026-02-22\n  - Causally matters: Capped the US medal count at 12 golds, finalizing their position as the runner-up and confirming Norway's unassailable lead.\n  - Source: [art_general_20260222_007_a44504a4], [art_sports_20260222_007_ecbd4ab5]\n\n# Evidence Mapping Table\n| Claim/Event | Article IDs | Date Support | Confidence (0-1) | Notes |\n|---|---|---|---|---|\n| Norway sets record with 18 golds and 41 total medals | [art_sports_20260223_008_c20fc878] | 2026-02-23 | 1.0 | Official final medal tallies. |\n| Klaebo wins 6 golds including 50km mass start | [art_sports_20260223_008_c20fc878], [art_general_20260221_017_57fbdfe9] | 2026-02-21 | 1.0 | Historic individual performance. |\n| Oftebro sweeps Nordic combined with 3 golds | [art_sports_20260223_008_c20fc878] | 2026-02-23 | 0.9 | Matches Samppa Lajunen's 2002 feat. |\n| Dale-Skjevdal wins 15km biathlon (17th gold) | [art_sports_20260222_007_ecbd4ab5] | 2026-02-20 | 1.0 | Perfect 20/20 shooting mentioned. |\n| US finishes second with 12 golds (incl. hockey) | [art_general_20260222_007_a44504a4], [art_sports_20260222_007_ecbd4ab5] | 2026-02-22 | 1.0 | US beat Canada in OT. |\n\n# Uncertainties And Alternative Paths\nThe primary alternative path would have required catastrophic underperformance by Norwegian athletes in cross-country skiing and biathlon. Had illness or severe waxing issues affected the Norwegian ski team (as occasionally happens in Nordic sports), countries like the United States or the Netherlands could have narrowed the gap. However, the sheer margin of victory (18 to 12) means multiple top Norwegian favorites would have needed to fail simultaneously for the outcome to change.\n",
    "is_polymarket": false,
    "is_overlap": true,
    "market_open": "2026-02-06T00:00:00+00:00",
    "market_open_estimated": false,
    "market_close": "2026-02-22T23:59:59+00:00",
    "polymarket_url": null,
    "price_data": null,
    "events": [
      {
        "id": "evt_sports_20260206_001_c2d97cb4",
        "date": "2026-02-06 00:00",
        "title": "Norway establishes systemic advantages in Nordic skiing",
        "description": "Norway's deep-rooted systemic advantages and talent pipeline in Nordic skiing disciplines.",
        "impact": "**Affects:** Option 1: Norway  \n\n**Direction:** Towards outcome    \n\n**Reasoning:**\nEvent evt_sports_20260206_001_c2d97cb4 had a positive impact on Norway winning.",
        "has_impact": true,
        "in_market_window": false,
        "source_url": "https://www.nbcolympics.com/news/final-medal-count-2026-milan-cortina-winter-olympics-and-paralympics",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_sports_20260220_004_bd419d95",
        "date": "2026-02-20 12:00",
        "title": "Johannes Dale-Skjevdal wins 15km mass start biathlon",
        "description": "Johannes Dale-Skjevdal hits all 20 targets in the 15-kilometer mass start biathlon, securing Norway's 17th gold medal.",
        "impact": "**Affects:** Option 1: Norway  \n\n**Direction:** Towards outcome    \n\n**Reasoning:**\nEvent evt_sports_20260220_004_bd419d95 had a positive impact on Norway winning.",
        "has_impact": true,
        "in_market_window": false,
        "source_url": "https://www.cbsnews.com/news/olympic-medal-count-2026-winter-games",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_sports_20260221_003_92d0ced9",
        "date": "2026-02-21 08:30",
        "title": "Klaebo wins the men's 50km mass start",
        "description": "Klaebo wins the men's 50km cross-country mass start.",
        "impact": "**Affects:** Option 1: Norway  \n\n**Direction:** Towards outcome    \n\n**Reasoning:**\nWinning the 50km mass start secured the 18th gold medal, contributing to Norway's win.",
        "has_impact": true,
        "in_market_window": false,
        "source_url": "https://www.cnn.com/sport/live-news/milan-winter-olympics-results-highlights-medals-02-21-26",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_sports_20260222_006_c53fdbc9",
        "date": "2026-02-22 12:00",
        "title": "Jordan Stolz wins three speedskating golds",
        "description": "Jordan Stolz wins three speedskating golds for the US.",
        "impact": "**Affects:** Option 1: Norway  \n\n**Direction:** Against outcome    \n\n**Reasoning:**\nEvent evt_sports_20260222_006_c53fdbc9 had a negative impact on Norway winning.",
        "has_impact": true,
        "in_market_window": false,
        "source_url": "https://heavy.com/sports/olympics/usa-gold-medal-count-today",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_sports_20260206_002_d3f998c3",
        "date": "2026-02-06 00:00",
        "title": "Generational talents emerge in Norway",
        "description": "The emergence of dominant individual athletes capable of sweeping multiple events.",
        "impact": "**Affects:** Option 1: Norway  \n\n**Direction:** Towards outcome    \n\n**Reasoning:**\nEvent evt_sports_20260206_002_d3f998c3 had a positive impact on Norway winning.",
        "has_impact": true,
        "in_market_window": false,
        "source_url": "https://www.nbcolympics.com/news/final-medal-count-2026-milan-cortina-winter-olympics-and-paralympics",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_sports_20260220_001_6f1bed3a",
        "date": "2026-02-20 12:00",
        "title": "Johannes Dale-Skjevdal hits all 20 targets in 15km biathlon",
        "description": "Johannes Dale-Skjevdal hits all 20 targets in the 15-kilometer mass start biathlon.",
        "impact": "**Affects:** Option 1: Norway  \n\n**Direction:** Towards outcome    \n\n**Reasoning:**\nHitting all targets led to winning the biathlon and securing the 17th gold, contributing to Norway's win.",
        "has_impact": true,
        "in_market_window": false,
        "source_url": "https://www.cbsnews.com/news/olympic-medal-count-2026-winter-games",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_sports_20260221_011_525b56ab",
        "date": "2026-02-21 08:00",
        "title": "Johannes Hoesflot Klaebo wins six gold medals",
        "description": "Johannes Hoesflot Klaebo wins six gold medals across cross-country skiing events, including the 50km mass start.",
        "impact": "**Affects:** Option 1: Norway  \n\n**Direction:** Towards outcome    \n\n**Reasoning:**\nEvent evt_sports_20260221_011_525b56ab had a positive impact on Norway winning.",
        "has_impact": true,
        "in_market_window": false,
        "source_url": "https://www.nbcolympics.com/news/final-medal-count-2026-milan-cortina-winter-olympics-and-paralympics",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_sports_20260221_004_a32ea3f8",
        "date": "2026-02-21 08:45",
        "title": "Norway secures its 18th gold medal",
        "description": "Klaebo's 50km cross-country mass start victory secures Norway's 18th gold medal.",
        "impact": "**Affects:** Option 1: Norway  \n\n**Direction:** Towards outcome    \n\n**Reasoning:**\nSecuring the 18th gold directly led to the final record of 18 golds, contributing to Norway's win.",
        "has_impact": true,
        "in_market_window": false,
        "source_url": "https://www.cnn.com/sport/live-news/milan-winter-olympics-results-highlights-medals-02-21-26",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_sports_20260221_003_5d6511de",
        "date": "2026-02-21 12:00",
        "title": "Jens Luras Oftebro wins three gold medals",
        "description": "Jens Luras Oftebro goes undefeated to win three golds in Nordic combined.",
        "impact": "**Affects:** Option 1: Norway  \n\n**Direction:** Towards outcome    \n\n**Reasoning:**\nEvent evt_sports_20260221_003_5d6511de had a positive impact on Norway winning.",
        "has_impact": true,
        "in_market_window": false,
        "source_url": "https://www.nbcolympics.com/news/final-medal-count-2026-milan-cortina-winter-olympics-and-paralympics",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_sports_20260221_005_7f3b7d79",
        "date": "2026-02-21 12:00",
        "title": "Norway accumulates 25 medals in cross-country and biathlon",
        "description": "Norway's dominance in events with numerous medal opportunities (cross-country and biathlon accounted for 25 medals).",
        "impact": "**Affects:** Option 1: Norway  \n\n**Direction:** Towards outcome    \n\n**Reasoning:**\nEvent evt_sports_20260221_005_7f3b7d79 had a positive impact on Norway winning.",
        "has_impact": true,
        "in_market_window": false,
        "source_url": "https://www.nbcolympics.com/news/final-medal-count-2026-milan-cortina-winter-olympics-and-paralympics",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      }
    ]
  }
];