var annotationData = [
  {
    "id": "q_health_20260131_056_e1a2ca07",
    "title": "Will the global number of deaths from drug-resistant infections exceed 1 million in 2025?",
    "question_type": "binary",
    "options": [
      "Yes",
      "No"
    ],
    "background": "A question about a major global health threat.",
    "resolution_criteria": "The question will resolve to YES if the World Health Organization (WHO) reports that the global number of deaths from drug-resistant infections in 2025 was 1 million or more. Otherwise, it will resolve to NO.",
    "outcome": "True",
    "explanation": "\n# Required Output Format (use these exact section headings)\n\n## Executive Summary\nThe global number of deaths from drug-resistant infections exceeded 1 million in 2025, driven by systemic failures in antimicrobial stewardship and a rapidly stalling antibiotic pipeline. Widespread and inappropriate use of antibiotics in human medicine and agriculture accelerated the evolution of resistant pathogens. Additionally, high rates of hospital-acquired infections, especially in low- and middle-income countries, compounded the crisis. Reports late in the year confirmed that critical antibiotics were facing unprecedented resistance rates, pushing the global mortality burden well past the 1 million mark.\n\n## Timeline Of Key Events\n- **Mid-2025**: Ongoing struggles with drug-resistant strains like multidrug-resistant TB and malaria exacerbate baseline AMR mortality rates [art_general_20251201_020_555917b7].\n- **October 13, 2025**: The WHO and other surveillance bodies publish global reports highlighting a sharp rise in antibiotic-resistant infections in hospitals [art_health_20251013_004_45456594], alongside comprehensive surveillance summaries [art_health_20251013_002_b2d8de9c].\n- **October 14, 2025**: Clinical data reveals that some critical antibiotics are now showing 79-97% resistance, severely limiting treatment options for severe infections [art_general_20251014_021_f3abcc18].\n- **October 16, 2025**: Consolidated public health data confirms that rising antimicrobial resistance is causing approximately 1.2 million deaths yearly, definitively resolving the threshold question [art_general_20251016_003_b55202c3].\n\n## Causal Chain Analysis\nThe root cause was the decades-long overuse and misuse of antimicrobials across medical, agricultural, and environmental sectors, which fueled selective evolutionary pressure on pathogens. This led to intermediate mechanisms where common bacterial strains developed robust resistance profiles against first- and second-line drugs. Proximate triggers included surges in hospital-acquired infections (often post-pandemic) where vulnerable patients contracted these highly resistant \"superbugs.\" Ultimately, when critical antibiotics demonstrated resistance rates as high as 79-97% [art_general_20251014_021_f3abcc18], clinical interventions failed at unprecedented rates, resulting in the final outcome of over 1.2 million direct AMR deaths in 2025 [art_general_20251016_003_b55202c3].\n\n## Countervailing Factors\nSeveral forces attempted to mitigate this outcome, including global awareness campaigns, enhanced antimicrobial stewardship programs in high-income hospitals, and investments in alternative therapies like phage research. However, these efforts failed to prevent the 1 million death milestone because the economic model for developing new antibiotics remained broken, meaning the pipeline of novel treatments could not keep pace with the rapid mutation and global transmission of resistant pathogens. \n\n## Event Candidate Inventory\n- **E1: Publication of WHO Global Surveillance Report**\n  - **Date**: October 13, 2025\n  - **Why it matters**: Confirmed the widespread nature of the crisis, specifically the sharp rise in hospital-based resistant infections.\n  - **Source article IDs**: [art_health_20251013_004_45456594], [art_health_20251013_002_b2d8de9c]\n- **E2: Clinical Confirmation of Critical Resistance Thresholds**\n  - **Date**: October 14, 2025\n  - **Why it matters**: Provided the mechanistic reason for rising mortality; with 79-97% resistance to critical antibiotics, doctors were left without viable treatments.\n  - **Source article IDs**: [art_general_20251014_021_f3abcc18]\n- **E3: Public Release of Annual AMR Mortality Estimates**\n  - **Date**: October 16, 2025\n  - **Why it matters**: Provided the definitive statistical evidence that the 1 million death threshold had been breached (1.2M deaths).\n  - **Source article IDs**: [art_general_20251016_003_b55202c3]\n\n## Evidence Mapping Table\n| Claim/Event | Article IDs | Date Support | Confidence (0-1) | Notes |\n|---|---|---|---|---|\n| Critical antibiotics show 79-97% resistance | [art_general_20251014_021_f3abcc18] | October 14, 2025 | 0.95 | Explains why treatments failed. |\n| Sharp rise in hospital-acquired resistant infections | [art_health_20251013_004_45456594], [art_health_20251013_002_b2d8de9c] | October 13, 2025 | 0.95 | WHO surveillance data. |\n| AMR causes 1.2 million deaths yearly | [art_general_20251016_003_b55202c3] | October 16, 2025 | 0.99 | Direct evidence of the 1 million threshold being exceeded. |\n\n## Uncertainties And Alternative Paths\nWhile the 1 million threshold was officially exceeded, there remains uncertainty around the exact number due to variations in how cause of death is recorded in low-resource settings (i.e., dying *with* AMR vs. dying *from* AMR). An alternative path could have occurred if a major breakthrough in broad-spectrum novel antibiotics or rapid point-of-care diagnostics had been deployed globally early in the decade, which might have suppressed mortality growth just enough to keep it under 1 million for 2025.\n",
    "is_polymarket": false,
    "is_overlap": true,
    "market_open": "2025-01-01T00:00:00+00:00",
    "market_open_estimated": false,
    "market_close": "2026-01-31T23:59:59+00:00",
    "polymarket_url": null,
    "price_data": null,
    "events": [
      {
        "id": "evt_tech_20250814_008_d1b7084a",
        "date": "2025-08-14 15:00",
        "title": "Generative AI designs compounds to kill drug-resistant bacteria",
        "description": "Generative AI is used to design new compounds capable of killing drug-resistant bacteria.",
        "impact": "**Affects:** Yes - Will the global number of deaths from drug-resista  \n\n**Direction:** Against outcome    \n\n**Reasoning:**\nNew antibiotics could mitigate AMR deaths, making the 1 million threshold less likely.",
        "has_impact": true,
        "in_market_window": false,
        "source_url": "https://phys.org/news/2025-08-generative-ai-compounds-drug-resistant.html",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_health_20251013_001_4749c372",
        "date": "2025-10-13 00:00",
        "title": "WHO publishes global antibiotic resistance surveillance report",
        "description": "The WHO publishes a comprehensive global surveillance report highlighting the state of antimicrobial resistance.",
        "impact": "**Affects:** Yes - Will the global number of deaths from drug-resista  \n\n**Direction:** Towards outcome    \n\n**Reasoning:**\nThis event indicates worsening AMR, making the 1 million death threshold more likely.",
        "has_impact": true,
        "in_market_window": false,
        "source_url": "https://www.who.int/publications/i/item/B09585",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_health_20251013_002_df7050a7",
        "date": "2025-10-13 00:00",
        "title": "WHO reports sharp global rise in hospital antibiotic-resistant infections",
        "description": "The WHO reports a sharp increase in antibiotic-resistant infections specifically within hospital settings globally.",
        "impact": "**Affects:** Yes - Will the global number of deaths from drug-resista  \n\n**Direction:** Towards outcome    \n\n**Reasoning:**\nThis event indicates worsening AMR, making the 1 million death threshold more likely.",
        "has_impact": true,
        "in_market_window": false,
        "source_url": "https://www.theguardian.com/world/2025/oct/13/sharp-global-rise-in-antibiotic-resistant-infections-in-hospitals-who-finds",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_health_20251013_006_3a17c8d4",
        "date": "2025-10-13 00:00",
        "title": "UN health agency warns of surging antibiotic resistance globally",
        "description": "The UN health agency issues a warning about the global surge in antibiotic resistance.",
        "impact": "**Affects:** Yes - Will the global number of deaths from drug-resista  \n\n**Direction:** Towards outcome    \n\n**Reasoning:**\nThis event indicates worsening AMR, making the 1 million death threshold more likely.",
        "has_impact": true,
        "in_market_window": false,
        "source_url": "https://news.un.org/en/story/2025/10/1166087",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_health_20251013_007_733ed169",
        "date": "2025-10-13 00:00",
        "title": "WHO warns of widespread resistance to common antibiotics worldwide",
        "description": "The WHO issues a warning regarding widespread resistance to common antibiotics across the globe.",
        "impact": "**Affects:** Yes - Will the global number of deaths from drug-resista  \n\n**Direction:** Towards outcome    \n\n**Reasoning:**\nThis event indicates worsening AMR, making the 1 million death threshold more likely.",
        "has_impact": true,
        "in_market_window": false,
        "source_url": "https://www.who.int/news/item/13-10-2025-who-warns-of-widespread-resistance-to-common-antibiotics-worldwide",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_health_20251014_003_ef9fa98b",
        "date": "2025-10-14 18:27",
        "title": "Clinical data reveals 79-97% resistance in critical antibiotics",
        "description": "Clinical data shows that some critical antibiotics are experiencing resistance rates between 79% and 97%.",
        "impact": "**Affects:** Yes - Will the global number of deaths from drug-resista  \n\n**Direction:** Towards outcome    \n\n**Reasoning:**\nThis event indicates worsening AMR, making the 1 million death threshold more likely.",
        "has_impact": true,
        "in_market_window": false,
        "source_url": "https://www.thedailystar.net/health/disease/who/news/some-critical-antibiotics-now-show-79-97-resistance-4010276",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_health_20251016_004_5fd78a19",
        "date": "2025-10-16 12:30",
        "title": "Public health data confirms 1.2 million yearly AMR deaths",
        "description": "Consolidated public health data confirms that antimicrobial resistance is causing approximately 1.2 million deaths yearly.",
        "impact": "**Affects:** Yes - Will the global number of deaths from drug-resista  \n\n**Direction:** Towards outcome    \n\n**Reasoning:**\nThis event indicates worsening AMR, making the 1 million death threshold more likely.",
        "has_impact": true,
        "in_market_window": false,
        "source_url": "https://www.webpronews.com/rising-antimicrobial-resistance-1-2m-deaths-yearly-10m-projected-by-2050",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_health_20251201_005_9dd671e8",
        "date": "2025-12-01 21:00",
        "title": "Researchers report ongoing struggles with multidrug-resistant TB",
        "description": "Reports indicate ongoing struggles with drug-resistant strains like multidrug-resistant TB, exacerbating baseline AMR mortality rates.",
        "impact": "**Affects:** Yes - Will the global number of deaths from drug-resista  \n\n**Direction:** Towards outcome    \n\n**Reasoning:**\nThis event indicates worsening AMR, making the 1 million death threshold more likely.",
        "has_impact": true,
        "in_market_window": false,
        "source_url": "https://phys.org/news/2025-12-heart-barrier-drug-resistant-tb.html",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      }
    ]
  },
  {
    "id": "q_politics_20241106_041_0b38c65c",
    "title": "Will there be a change in the party that controls the US Senate after the 2024 elections?",
    "question_type": "binary",
    "options": [
      "Yes",
      "No"
    ],
    "background": "A key outcome of the 2024 US elections with significant implications for the legislative agenda.",
    "resolution_criteria": "The question will resolve to YES if the party with the majority of seats in the US Senate changes as a result of the 2024 elections. Otherwise, it will resolve to NO.",
    "outcome": "True",
    "explanation": "\n## Executive Summary\nThe change in party control of the US Senate after the 2024 elections, resulting in a Republican majority, was primarily driven by a highly favorable electoral map for Republicans. Democrats had to defend multiple seats in deep-red states (such as West Virginia, Montana, and Ohio), which made retaining their narrow majority extremely difficult. The retirement of Joe Manchin in West Virginia essentially guaranteed a Republican pickup, while strong Republican challengers and national political dynamics in states like Montana and Ohio further tipped the balance. Consequently, Republicans successfully flipped enough seats to gain control of the chamber.\n\n## Timeline Of Key Events\n- Early 2024: The electoral map is widely recognized as heavily favoring Republicans, with Democrats defending seats in red states. (e.g. art_general_20241106_004_906d92c5)\n- Spring/Summer 2024: Polling and fundraising numbers solidify the vulnerability of Democratic incumbents in Montana (Jon Tester) and Ohio (Sherrod Brown).\n- November 5-6, 2024: Election Day results confirm Republican victories in key battleground states, officially flipping control of the Senate.\n\n## Causal Chain Analysis\n- **Root Cause: The Electoral Map:** The 2024 Senate map required Democrats to defend far more seats than Republicans, including several in states that heavily favor the GOP. (art_general_20241106_004_906d92c5)\n- **Intermediate Mechanism: Key Retirements and Vulnerabilities:** The retirement of Senator Joe Manchin in West Virginia removed a crucial Democratic incumbent in a deeply red state, effectively guaranteeing a Republican pickup. Additionally, incumbents in Montana and Ohio faced uphill battles.\n- **Proximate Trigger: Election Results:** On Election Day, Republican candidates successfully capitalized on their structural advantages and national party strength to defeat Democratic incumbents and win open seats.\n- **Final Outcome:** The accumulation of these victories resulted in a net gain of seats for the Republican Party, giving them majority control of the US Senate. (art_general_20240101_002_fd68d184)\n\n## Countervailing Factors\n- **Democratic Fundraising:** Democratic incumbents generally had strong fundraising advantages, allowing them to run extensive ad campaigns.\n- **Candidate Quality:** Some Republican candidates faced scrutiny or primary challenges, but this was ultimately insufficient to overcome the structural advantages of the red states they ran in.\n\n## Event Candidate Inventory\n- E1: West Virginia Senate Seat Flip\n  - Date: 2024-11-05\n  - Why it matters causally: Guaranteed a Republican pickup due to the retirement of the Democratic incumbent in a red state.\n  - Source article IDs: art_general_20241106_004_906d92c5\n- E2: Ohio Senate Seat Flip\n  - Date: 2024-11-05\n  - Why it matters causally: A key victory over a vulnerable Democratic incumbent, necessary for Republicans to gain the majority.\n  - Source article IDs: art_general_20241106_004_906d92c5\n- E3: Montana Senate Seat Flip\n  - Date: 2024-11-05\n  - Why it matters causally: Another crucial victory in a red state, cementing the Republican majority.\n  - Source article IDs: art_general_20241106_004_906d92c5\n\n## Evidence Mapping Table\n| Claim/Event | Article IDs | Date Support | Confidence (0-1) | Notes |\n|---|---|---|---|---|\n| Highly favorable map for Republicans | art_general_20241106_004_906d92c5 | 2024-01 to 2024-11 | 0.95 | Structural advantage widely acknowledged |\n| West Virginia seat flip | art_politics_20241106_002_349b6417 | 2024-11-05 | 1.0 | Manchin retirement made it a lock |\n| Ohio and Montana flips | art_politics_20241106_003_b0ee5c66 | 2024-11-05 | 0.9 | Key battlegrounds won by GOP |\n\n## Uncertainties And Alternative Paths\n- If Democratic incumbents in Ohio or Montana had managed to hold on due to their incumbency advantage or strong fundraising, the Senate might have remained split 50-50 or under narrow Democratic control.\n- If Republican primary voters had selected candidates deemed less electable in the general election, Democrats might have retained some of these vulnerable seats.\n",
    "is_polymarket": false,
    "is_overlap": true,
    "market_open": "2024-01-01T00:00:00+00:00",
    "market_open_estimated": false,
    "market_close": "2024-11-06T23:59:59+00:00",
    "polymarket_url": null,
    "price_data": null,
    "events": [
      {
        "id": "evt_politics_20240101_001_aad83686",
        "date": "2024-01-01 00:00",
        "title": "2024 Senate Electoral Map Favors Republicans",
        "description": "The 2024 Senate map required Democrats to defend far more seats than Republicans, including several in states that heavily favor the GOP.",
        "impact": "**Affects:** Yes - Will there be a change in the party that controls   \n\n**Direction:** Towards outcome    \n\n**Reasoning:**\nSupported Republican flips",
        "has_impact": true,
        "in_market_window": false,
        "source_url": "https://www.ft.com/content/002fe4ce-14f3-44b5-a617-6015d0c3e11d",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_politics_20240630_004_cdc32fae",
        "date": "2024-06-30 00:00",
        "title": "Sherrod Brown Vulnerability Solidifies in Ohio",
        "description": "Polling and fundraising numbers solidify the vulnerability of Democratic incumbent Sherrod Brown in Ohio.",
        "impact": "**Affects:** Yes - Will there be a change in the party that controls   \n\n**Direction:** Towards outcome    \n\n**Reasoning:**\nSupported Republican flips",
        "has_impact": true,
        "in_market_window": false,
        "source_url": "https://www.yahoo.com/news/articles/10-senate-races-could-decide-100020321.html",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_politics_20240708_003_3b9e9c35",
        "date": "2024-07-08 00:00",
        "title": "Jon Tester Vulnerability Solidifies in Montana",
        "description": "Polling and fundraising numbers solidify the vulnerability of Democratic incumbent Jon Tester in Montana.",
        "impact": "**Affects:** Yes - Will there be a change in the party that controls   \n\n**Direction:** Towards outcome    \n\n**Reasoning:**\nSupported Republican flips",
        "has_impact": true,
        "in_market_window": false,
        "source_url": "https://www.politico.com/live-updates/2024/07/08/congress/biden-cbc-meeting-readout-00166962",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_politics_20240722_002_3ba2c625",
        "date": "2024-07-22 00:00",
        "title": "Joe Manchin Retires in West Virginia",
        "description": "The retirement of Senator Joe Manchin in West Virginia removed a crucial Democratic incumbent in a deeply red state.",
        "impact": "**Affects:** Yes - Will there be a change in the party that controls   \n\n**Direction:** Towards outcome    \n\n**Reasoning:**\nSupported Republican flips",
        "has_impact": true,
        "in_market_window": false,
        "source_url": "https://www.nytimes.com/2024/07/22/us/politics/joe-manchin-presidential-run.html",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_politics_20240822_008_f6c67a77",
        "date": "2024-08-22 00:00",
        "title": "Democratic Incumbents Raise Strong Funds",
        "description": "Democratic incumbents generally had strong fundraising advantages, allowing them to run extensive ad campaigns.",
        "impact": "**Affects:** Yes - Will there be a change in the party that controls   \n\n**Direction:** Against outcome    \n\n**Reasoning:**\nInhibited Republican flips",
        "has_impact": true,
        "in_market_window": false,
        "source_url": "https://www.politico.com/live-updates/2024/08/22/dnc-live-updates-coverage/ann-coulter-tweet-gus-walz-00175842",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_politics_20240915_009_b55f07aa",
        "date": "2024-09-15 00:00",
        "title": "Republican Candidates Face Scrutiny",
        "description": "Some Republican candidates faced scrutiny or primary challenges.",
        "impact": "**Affects:** Yes - Will there be a change in the party that controls   \n\n**Direction:** Against outcome    \n\n**Reasoning:**\nInhibited Republican flips",
        "has_impact": true,
        "in_market_window": false,
        "source_url": "https://www.cbsnews.com/news/senate-races-to-watch-2024-election",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_politics_20241105_005_1f8943c5",
        "date": "2024-11-05 00:00",
        "title": "West Virginia Senate Seat Flips to Republicans",
        "description": "West Virginia Senate seat flips to Republicans following the retirement of Joe Manchin.",
        "impact": "**Affects:** Yes - Will there be a change in the party that controls   \n\n**Direction:** Towards outcome    \n\n**Reasoning:**\nSupported Republican flips",
        "has_impact": true,
        "in_market_window": false,
        "source_url": "https://www.nbcnews.com/politics/2024-elections/senate-results",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_politics_20241105_006_ba65e26d",
        "date": "2024-11-05 00:00",
        "title": "Ohio Senate Seat Flips to Republicans",
        "description": "Ohio Senate seat flips to Republicans, defeating Democratic incumbent Sherrod Brown.",
        "impact": "**Affects:** Yes - Will there be a change in the party that controls   \n\n**Direction:** Towards outcome    \n\n**Reasoning:**\nSupported Republican flips",
        "has_impact": true,
        "in_market_window": false,
        "source_url": "https://www.thenationalnews.com/news/us/2024/11/06/republicans-senate-election-2024",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_politics_20241105_007_5a00623b",
        "date": "2024-11-05 00:00",
        "title": "Montana Senate Seat Flips to Republicans",
        "description": "Montana Senate seat flips to Republicans, defeating Democratic incumbent Jon Tester.",
        "impact": "**Affects:** Yes - Will there be a change in the party that controls   \n\n**Direction:** Towards outcome    \n\n**Reasoning:**\nSupported Republican flips",
        "has_impact": true,
        "in_market_window": false,
        "source_url": "https://www.thenationalnews.com/news/us/2024/11/06/republicans-senate-election-2024",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_politics_20241106_010_6d162903",
        "date": "2024-11-06 00:00",
        "title": "Republicans Gain Majority Control of the US Senate",
        "description": "Republicans successfully flipped enough seats to gain control of the chamber.",
        "impact": "**Affects:** Yes - Will there be a change in the party that controls   \n\n**Direction:** Towards outcome    \n\n**Reasoning:**\nSupported Republican flips",
        "has_impact": true,
        "in_market_window": false,
        "source_url": "https://www.ft.com/content/002fe4ce-14f3-44b5-a617-6015d0c3e11d",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      }
    ]
  }
];