var annotationData = [
  {
    "id": "q_culture_20260219_003_2b36f0d3",
    "title": "Which film won the Best Film award at the 2026 BAFTA Film Awards?",
    "question_type": "mcq",
    "options": [
      "One Battle After Another",
      "Sinners",
      "I Swear",
      "The Holdovers"
    ],
    "background": "The 79th British Academy Film Awards (BAFTAs) were held on February 18, 2026, honoring the best in film for 2025.",
    "resolution_criteria": "The question resolves to the film that officially won the Best Film award at the 2026 British Academy Film Awards.",
    "outcome": "One Battle After Another",
    "explanation": "\n# Executive Summary\nThe film \"One Battle After Another\" dominated the 2026 BAFTA Film Awards, culminating in winning the prestigious Best Film award. Early momentum was established when it led the BAFTA longlists with a record-breaking 16 mentions and followed up with a commanding 14 nominations, making it a clear frontrunner. Competing films like \"Sinners\" and \"Hamnet\" won important secondary categories, but \"One Battle After Another\" maintained its broad, undeniable industry support to secure the night's top honor, alongside five other key victories, cementing its status as the most celebrated film of the year.\n\n## Timeline Of Key Events\n- **2026-01-09**: The BAFTA longlists were announced. \"One Battle After Another\" led all films with 16 mentions, becoming the most longlisted film in BAFTA history [art_culture_20260212_019_be7fe7da].\n- **2026-01-27**: The BAFTA nominations were officially announced. \"One Battle After Another\" received the most nominations with 14, establishing itself as the leading contender [art_culture_20260212_019_be7fe7da].\n- **2026-02-22**: The 79th British Academy Film Awards took place at the Royal Festival Hall in London [art_culture_20260212_019_be7fe7da]. \"One Battle After Another\" won six awards, including Best Film [art_culture_20260215_021_e366ae96].\n- **2026-02-22**: During the ceremony, \"Sinners\" won three awards (including Original Score, Original Screenplay, and Supporting Actress), but its success was overshadowed by a high-profile controversy during the broadcast [art_culture_20260204_013_7a3060fe].\n\n## Causal Chain Analysis\nThe sweeping success of \"One Battle After Another\" was driven by widespread acclaim that was formalized early in the awards season. This widespread industry backing caused it to break the record for the most BAFTA longlist mentions (16) [art_culture_20260212_019_be7fe7da]. This unprecedented early support led to a commanding lead in the final nominations, securing 14 nods. Because it was the clear favorite across multiple technical and major categories, the film carried unstoppable momentum into the final voting phase, which ultimately resulted in its victory for Best Film along with five other awards [art_culture_20260215_021_e366ae96].\n\n## Countervailing Factors\nThe main countervailing force was the film \"Sinners,\" which had strong momentum, particularly following historical achievements by its Black director Ryan Coogler and widespread acclaim for its original screenplay and acting [art_culture_20260212_019_be7fe7da]. \"Sinners\" secured 13 nominations and ultimately won three major awards. However, \"Sinners\" could not overcome the sheer breadth of support across all voting branches that \"One Battle After Another\" commanded.\n\n## Event Candidate Inventory\n- **E1**: BAFTA longlist announcement establishing \"One Battle After Another\" as the frontrunner.\n  - Date: 2026-01-09\n  - Why it matters causally: Broke the record for most longlist mentions, signaling overwhelming early industry support.\n  - Source article IDs: [art_culture_20260212_019_be7fe7da]\n- **E2**: BAFTA nomination announcement.\n  - Date: 2026-01-27\n  - Why it matters causally: Translated longlist momentum into 14 official nominations, cementing its frontrunner status.\n  - Source article IDs: [art_culture_20260212_019_be7fe7da]\n- **E3**: \"One Battle After Another\" wins Best Film at the 79th BAFTA Film Awards.\n  - Date: 2026-02-22\n  - Why it matters causally: The final outcome resolving the question.\n  - Source article IDs: [art_culture_20260215_021_e366ae96]\n\n## Evidence Mapping Table\n| Claim/Event | Article IDs | Date Support | Confidence (0-1) | Notes |\n|---|---|---|---|---|\n| \"One Battle After Another\" breaks BAFTA longlist record (16 mentions) | [art_culture_20260212_019_be7fe7da] | 2026-01-09 | 1.0 | Clear historical milestone. |\n| \"One Battle After Another\" receives most nominations (14) | [art_culture_20260212_019_be7fe7da] | 2026-01-27 | 1.0 | Confirms frontrunner status. |\n| \"Sinners\" receives 13 nominations and wins 3 awards | [art_culture_20260212_019_be7fe7da], [art_culture_20260204_013_7a3060fe] | 2026-02-22 | 1.0 | Main competitor. |\n| \"One Battle After Another\" wins Best Film | [art_culture_20260215_021_e366ae96] | 2026-02-22 | 1.0 | The resolved outcome. |\n\n## Uncertainties And Alternative Paths\nThe primary alternative path would have been a victory for \"Sinners,\" which won Original Screenplay and Supporting Actress. If \"Sinners\" had secured a few more key wins (such as Director or Best Actor), it might have carried the Best Film prize. However, the historic and widespread support for \"One Battle After Another\" across all branches made this highly unlikely.\n",
    "is_polymarket": false,
    "is_overlap": true,
    "market_open": "2026-01-18T00:00:00+00:00",
    "market_open_estimated": false,
    "market_close": "2026-02-19T00:00:00+00:00",
    "polymarket_url": null,
    "price_data": null,
    "events": [
      {
        "id": "evt_culture_20260109_001_6d93a752",
        "date": "2026-01-09 12:00",
        "title": "BAFTA longlists announced",
        "description": "The BAFTA longlists were announced for the 2026 awards.",
        "impact": "**Affects:** Option 1: One Battle After Another  \n\n**Direction:** Towards outcome    \n\n**Reasoning:**\nThis event contributed to the final outcome.",
        "has_impact": true,
        "in_market_window": false,
        "source_url": "https://en.wikipedia.org/wiki/79th_British_Academy_Film_Awards",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_culture_20260204_008_adcba3d3",
        "date": "2026-02-04 09:00",
        "title": "Sinners wins three awards",
        "description": "Sinners won three awards including Original Score, Original Screenplay, and Supporting Actress.",
        "impact": "**Affects:** Option 1: One Battle After Another  \n\n**Direction:** Towards outcome    \n\n**Reasoning:**\nThis event contributed to the final outcome.",
        "has_impact": true,
        "in_market_window": false,
        "source_url": "https://www.ebony.com/sinners-bafta-2026-wins-onscreen-slur-incident",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_culture_20260215_010_a01c32bf",
        "date": "2026-02-15 09:00",
        "title": "One Battle After Another wins six awards",
        "description": "One Battle After Another won six awards at the ceremony.",
        "impact": "**Affects:** Option 1: One Battle After Another  \n\n**Direction:** Towards outcome    \n\n**Reasoning:**\nThis event contributed to the final outcome.",
        "has_impact": true,
        "in_market_window": false,
        "source_url": "https://www.telegraph.co.uk/films/2026/02/23/bafta-film-awards-2026-winners",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_culture_20260109_002_44444e2a",
        "date": "2026-01-09 12:00",
        "title": "One Battle After Another gets 16 longlist mentions",
        "description": "One Battle After Another led all films with 16 mentions on the BAFTA longlists.",
        "impact": "**Affects:** Option 1: One Battle After Another  \n\n**Direction:** Towards outcome    \n\n**Reasoning:**\nThis event contributed to the final outcome.",
        "has_impact": true,
        "in_market_window": false,
        "source_url": "https://en.wikipedia.org/wiki/79th_British_Academy_Film_Awards",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_culture_20260109_003_2e205092",
        "date": "2026-01-09 12:00",
        "title": "One Battle After Another breaks longlist record",
        "description": "One Battle After Another became the most longlisted film in BAFTA history.",
        "impact": "**Affects:** Option 1: One Battle After Another  \n\n**Direction:** Towards outcome    \n\n**Reasoning:**\nThis event contributed to the final outcome.",
        "has_impact": true,
        "in_market_window": false,
        "source_url": "https://en.wikipedia.org/wiki/79th_British_Academy_Film_Awards",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_culture_20260127_004_2c49e5b0",
        "date": "2026-01-27 12:00",
        "title": "BAFTA nominations officially announced",
        "description": "The BAFTA nominations were officially announced.",
        "impact": "**Affects:** Option 1: One Battle After Another  \n\n**Direction:** Towards outcome    \n\n**Reasoning:**\nThis event contributed to the final outcome.",
        "has_impact": true,
        "in_market_window": false,
        "source_url": "https://en.wikipedia.org/wiki/79th_British_Academy_Film_Awards",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_culture_20260127_005_f847a551",
        "date": "2026-01-27 12:00",
        "title": "One Battle After Another receives 14 nominations",
        "description": "One Battle After Another received the most nominations with 14.",
        "impact": "**Affects:** Option 1: One Battle After Another  \n\n**Direction:** Towards outcome    \n\n**Reasoning:**\nThis event contributed to the final outcome.",
        "has_impact": true,
        "in_market_window": false,
        "source_url": "https://en.wikipedia.org/wiki/79th_British_Academy_Film_Awards",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_culture_20260127_006_03487878",
        "date": "2026-01-27 12:00",
        "title": "Sinners receives 13 nominations",
        "description": "Sinners secured 13 nominations.",
        "impact": "**Affects:** Option 1: One Battle After Another  \n\n**Direction:** Towards outcome    \n\n**Reasoning:**\nThis event contributed to the final outcome.",
        "has_impact": true,
        "in_market_window": false,
        "source_url": "https://en.wikipedia.org/wiki/79th_British_Academy_Film_Awards",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_culture_20260204_009_a5939079",
        "date": "2026-02-04 09:30",
        "title": "High-profile controversy during broadcast",
        "description": "A high-profile controversy occurred during the broadcast, overshadowing Sinners' success.",
        "impact": "**Affects:** Option 1: One Battle After Another  \n\n**Direction:** Towards outcome    \n\n**Reasoning:**\nThis event contributed to the final outcome.",
        "has_impact": true,
        "in_market_window": false,
        "source_url": "https://www.ebony.com/sinners-bafta-2026-wins-onscreen-slur-incident",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_culture_20260212_007_f0c47a02",
        "date": "2026-02-12 09:00",
        "title": "79th British Academy Film Awards takes place",
        "description": "The 79th British Academy Film Awards took place at the Royal Festival Hall in London.",
        "impact": "**Affects:** Option 1: One Battle After Another  \n\n**Direction:** Towards outcome    \n\n**Reasoning:**\nThis event contributed to the final outcome.",
        "has_impact": true,
        "in_market_window": false,
        "source_url": "https://en.wikipedia.org/wiki/79th_British_Academy_Film_Awards",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      }
    ]
  },
  {
    "id": "q_finance_20231013_002_14a60e35",
    "title": "When will Microsoft close its acquisition of Activision Blizzard?",
    "question_type": "timeframe",
    "options": [
      "Q2 2023",
      "Q3 2023",
      "Q4 2023",
      "2024 or later"
    ],
    "background": "After being announced in early 2022, Microsoft's acquisition of Activision Blizzard faced significant regulatory scrutiny globally. In April 2023, the UK's CMA blocked the deal, creating major uncertainty about if and when it would close.",
    "resolution_criteria": "The question resolves to the timeframe corresponding to the official closing date of the acquisition, as announced by Microsoft.",
    "outcome": "Q4 2023",
    "explanation": "\n# Executive Summary\nThe closing of Microsoft's $68.7 billion acquisition of Activision Blizzard in Q4 2023 was primarily determined by successfully navigating three major regulatory hurdles across the EU, US, and UK. The European Commission approved the deal in May 2023 following concessions on cloud gaming. In the US, Microsoft won a crucial federal court case against the FTC in July 2023, effectively clearing the path stateside. Finally, after an initial block, the UK's Competition and Markets Authority (CMA) approved a restructured deal in October 2023, which divested cloud streaming rights to Ubisoft, triggering the immediate finalization of the acquisition on October 13, 2023.\n\n# Timeline Of Key Events\n- **May 15, 2023:** The European Commission approves the acquisition after Microsoft agrees to 10-year licensing deals for cloud gaming. [{art_tech_20231010_015_89adf659}]\n- **July 11, 2023:** A US federal judge denies the FTC's request for a preliminary injunction to block the deal, handing Microsoft a major legal victory. [{art_tech_20231008_014_5b9a0758}]\n- **July 14, 2023:** The US appeals court denies the FTC's motion to pause the acquisition, further clearing the US path. [{art_tech_20231008_031_60da2505}]\n- **August 22, 2023:** Microsoft submits a newly restructured deal to the UK CMA, agreeing to transfer cloud gaming rights for current and new Activision Blizzard games to Ubisoft for 15 years. [{art_tech_20231005_013_1961c5d7}]\n- **September 22, 2023:** The UK CMA signals preliminary approval of the restructured deal. [{art_tech_20231005_030_308f5b23}]\n- **October 13, 2023:** The UK CMA grants final official approval to the acquisition. [{art_tech_20231001_012_55c28dc0}]\n- **October 13, 2023:** Microsoft officially closes the acquisition of Activision Blizzard. [{art_tech_20230915_011_b48b4797}]\n\n# Causal Chain Analysis\nThe path to the Q4 2023 outcome was driven by a sequence of necessary regulatory clearances. The European Commission's early approval provided momentum but was insufficient on its own due to ongoing US and UK opposition. The FTC's attempt to secure a preliminary injunction in the US failed in July 2023, which caused the US regulatory threat to effectively collapse, shifting the entire focus to the UK CMA [{art_tech_20231008_014_5b9a0758}]. The CMA had originally blocked the deal over cloud gaming concerns. This led to Microsoft restructuring the deal by divesting global cloud gaming rights (excluding the EEA) to Ubisoft [{art_tech_20231005_013_1961c5d7}]. This massive concession directly resolved the CMA's core anti-competitive concerns, resulting in preliminary clearance in September and final approval on October 13. The CMA's green light was the proximate trigger that allowed Microsoft to immediately close the deal the exact same day [{art_tech_20231001_012_55c28dc0}].\n\n# Countervailing Factors\nThe primary countervailing factors were the concerted efforts by the FTC and CMA to block the deal over anti-competitive concerns, particularly in the nascent cloud gaming market. Sony also heavily lobbied against the deal, arguing it would restrict access to the Call of Duty franchise on PlayStation. These forces ultimately failed because Microsoft demonstrated a willingness to make binding, long-term structural concessions (like the Ubisoft divestiture and 10-year Nintendo/Sony contracts) and successfully defeated the FTC's weak legal arguments in federal court.\n\n# Event Candidate Inventory\n- **E1:** European Commission approves the acquisition.\n  - Date: May 15, 2023\n  - Causality: Provided the first major international regulatory green light.\n  - Source: [{art_tech_20231010_015_89adf659}]\n- **E2:** US Federal Judge denies FTC preliminary injunction.\n  - Date: July 11, 2023\n  - Causality: Removed the primary US legal roadblock preventing the deal's closure.\n  - Source: [{art_tech_20231008_014_5b9a0758}]\n- **E3:** Microsoft submits restructured deal with Ubisoft cloud divestiture to UK CMA.\n  - Date: August 22, 2023\n  - Causality: Directly addressed the CMA's block, opening a new path to UK approval.\n  - Source: [{art_tech_20231005_013_1961c5d7}]\n- **E4:** UK CMA gives final approval.\n  - Date: October 13, 2023\n  - Causality: The final regulatory hurdle cleared, allowing immediate closing.\n  - Source: [{art_tech_20231001_012_55c28dc0}]\n\n# Evidence Mapping Table\n| Claim/Event | Article IDs | Date Support | Confidence (0-1) | Notes |\n|---|---|---|---|---|\n| EU Approval | [{art_tech_20231010_015_89adf659}] | May 15, 2023 | 0.95 | Major initial clearance. |\n| FTC loses injunction | [{art_tech_20231008_014_5b9a0758}] | July 11, 2023 | 0.95 | Key legal victory for MS. |\n| Ubisoft restructuring | [{art_tech_20231005_013_1961c5d7}] | August 22, 2023 | 0.95 | Addressed UK CMA block. |\n| CMA final approval | [{art_tech_20231001_012_55c28dc0}] | October 13, 2023 | 1.00 | Proximate trigger for closing. |\n\n# Uncertainties And Alternative Paths\nThe primary alternative path was the deal completely collapsing if the FTC had won its preliminary injunction or if the CMA had rejected the restructured Ubisoft deal. The deadline to close had already been extended from July to October to allow time to negotiate with the CMA. If the October 18, 2023 deadline was missed without approval, Microsoft would have owed a $3 billion termination fee, making deal collapse highly plausible.\n",
    "is_polymarket": false,
    "is_overlap": true,
    "market_open": "2023-05-01T00:00:00+00:00",
    "market_open_estimated": false,
    "market_close": "2023-10-13T23:59:59+00:00",
    "polymarket_url": null,
    "price_data": null,
    "events": [
      {
        "id": "evt_tech_20230515_001_1565a4e6",
        "date": "2023-05-15 00:00",
        "title": "Microsoft agrees to 10-year licensing deals for cloud gaming",
        "description": "Microsoft agrees to 10-year licensing deals for cloud gaming to appease regulators.",
        "impact": "No impact assessment provided.",
        "has_impact": false,
        "in_market_window": false,
        "source_url": "https://www.geekwire.com/2025/nearly-two-years-later-ftc-drops-final-challenge-to-microsofts-activision-blizzard-deal",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_tech_20230515_002_b180cc0c",
        "date": "2023-05-15 12:00",
        "title": "European Commission approves the acquisition",
        "description": "The European Commission approves the acquisition after Microsoft agrees to 10-year licensing deals.",
        "impact": "No impact assessment provided.",
        "has_impact": false,
        "in_market_window": false,
        "source_url": "https://www.geekwire.com/2025/nearly-two-years-later-ftc-drops-final-challenge-to-microsofts-activision-blizzard-deal",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_tech_20230701_003_f1536728",
        "date": "2023-07-01 00:00",
        "title": "FTC attempts to secure a preliminary injunction",
        "description": "The FTC attempts to secure a preliminary injunction in the US to block the deal.",
        "impact": "No impact assessment provided.",
        "has_impact": false,
        "in_market_window": false,
        "source_url": "https://www.theverge.com/23768244/ftc-microsoft-activision-blizzard-case-news-announcements",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_tech_20230711_004_f5b1b5e3",
        "date": "2023-07-11 00:00",
        "title": "US Federal Judge denies FTC preliminary injunction",
        "description": "A US federal judge denies the FTC's request for a preliminary injunction to block the deal.",
        "impact": "No impact assessment provided.",
        "has_impact": false,
        "in_market_window": false,
        "source_url": "https://www.theverge.com/23768244/ftc-microsoft-activision-blizzard-case-news-announcements",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_tech_20230714_005_aefe7682",
        "date": "2023-07-14 00:00",
        "title": "US appeals court denies FTC's motion to pause the acquisition",
        "description": "The US appeals court denies the FTC's motion to pause the acquisition.",
        "impact": "No impact assessment provided.",
        "has_impact": false,
        "in_market_window": false,
        "source_url": "https://www.archyde.com/microsofts-69-billion-activision-blizzard-deal-cleared-after-ftc-legal-battle-ends",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_tech_20230801_006_3d3af3ee",
        "date": "2023-08-01 00:00",
        "title": "CMA originally blocks the deal",
        "description": "The CMA originally blocked the deal over cloud gaming concerns.",
        "impact": "No impact assessment provided.",
        "has_impact": false,
        "in_market_window": false,
        "source_url": "https://finance.yahoo.com/news/ftc-drops-case-over-microsoft-094531893.html",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_tech_20230822_007_08d517be",
        "date": "2023-08-22 00:00",
        "title": "Microsoft submits restructured deal with Ubisoft cloud divestiture",
        "description": "Microsoft submits a newly restructured deal to the UK CMA, agreeing to transfer cloud gaming rights to Ubisoft.",
        "impact": "No impact assessment provided.",
        "has_impact": false,
        "in_market_window": false,
        "source_url": "https://finance.yahoo.com/news/ftc-drops-case-over-microsoft-094531893.html",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_tech_20230922_008_431e1dc1",
        "date": "2023-09-22 00:00",
        "title": "UK CMA signals preliminary approval",
        "description": "The UK CMA signals preliminary approval of the restructured deal.",
        "impact": "No impact assessment provided.",
        "has_impact": false,
        "in_market_window": false,
        "source_url": "https://www.cnn.com/2023/10/13/tech/microsoft-activision-blizzard-takeover-uk-intl-hnk",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_tech_20231013_009_8721fb2e",
        "date": "2023-10-13 00:00",
        "title": "UK CMA grants final official approval",
        "description": "The UK CMA grants final official approval to the acquisition.",
        "impact": "No impact assessment provided.",
        "has_impact": false,
        "in_market_window": false,
        "source_url": "https://www.gov.uk/cma-cases/microsoft-slash-activision-blizzard-merger-inquiry",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_tech_20231013_010_25bc8a8e",
        "date": "2023-10-13 00:00",
        "title": "Microsoft officially closes the acquisition",
        "description": "Microsoft officially closes the acquisition of Activision Blizzard.",
        "impact": "No impact assessment provided.",
        "has_impact": false,
        "in_market_window": false,
        "source_url": "https://www.gov.uk/cma-cases/microsoft-slash-activision-blizzard-merger-inquiry",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      }
    ]
  }
];