var annotationData = [
  {
    "id": "q_health_20251231_027_902f17d9",
    "title": "Will the FDA approve at least one AI-powered diagnostic tool for autonomous use by radiologists in 2025?",
    "question_type": "binary",
    "options": [
      "Yes",
      "No"
    ],
    "background": "Inspired by the STAT News articles on the use of AI in medicine, this question explores a specific regulatory milestone.",
    "resolution_criteria": "The question will resolve to YES if the FDA grants marketing authorization to at least one AI-based medical imaging tool that can be used for diagnostic purposes without requiring a radiologist to review the images. Otherwise, it will resolve to NO.",
    "outcome": "True",
    "explanation": "\n## Executive Summary\nIn 2025, the FDA officially approved the first AI-powered diagnostic tools intended for autonomous use by radiologists. Driven by the critical shortage of radiologists and the overwhelming volume of imaging data, the medical industry continuously pushed for more independent AI systems. Throughout the year, the FDA established more robust frameworks for autonomous AI, culminating in key clearances in late 2025. This breakthrough resulted from a combination of advanced foundation models demonstrating high clinical efficacy and the FDA adapting its regulatory pathways (primarily 510(k)) to accommodate AI devices that learn and operate independently.\n\n## Timeline Of Key Events\n- **January - May 2025:** The FDA witnessed an ongoing surge in standard AI/ML device clearances under the 510(k) pathway, with radiology accounting for the vast majority. Discussions escalated around the need for autonomous diagnostic tools to alleviate radiologist burnout [art_general_20250101_005_a4ff6edb].\n- **June - July 2025:** The FDA released updated guidance and denied certain blanket exemption requests for radiology AI devices, asserting the necessity of rigorous premarket reviews to ensure safety for autonomous functions [art_general_20250108_005_25b11783]. Philips received clearance for the AI-powered Spectral CT Verida, showing AI's deep integration into hardware.\n- **August - October 2025:** Milestone clearances occurred as the FDA approved specialized tools (like Perimeter Medical Imaging AI's device for breast cancer and Guardant360 CDx enhancements) that pushed the boundary of clinical independence [art_health_20250625_015_12da4e25].\n- **November - December 2025:** The FDA officially cleared at least one fully autonomous AI diagnostic tool for radiological use, officially satisfying the resolution criteria by year's end [art_tech_20260409_009_ac882dfb].\n\n## Causal Chain Analysis\n1. **Technological Capability & Data Availability:** The rapid advancement in deep learning and foundation models allowed AI to achieve diagnostic accuracy comparable to or exceeding human radiologists in specific tasks. This *led to* increased confidence from medical device manufacturers to submit autonomous tools [art_general_20250101_005_a4ff6edb].\n2. **Healthcare System Pressures:** Severe shortages of radiologists and increased imaging volumes *caused* massive backlogs and burnout, creating a strong market demand for autonomous solutions that could operate without constant human oversight [art_health_20250101_007_b5de92a5].\n3. **FDA Regulatory Adaptation:** Recognizing the demand and the technological maturity, the FDA adapted its evaluation frameworks. Although they denied blanket exemptions to maintain safety, they provided clear guidelines for autonomous systems. This structured regulatory pathway *resulted in* manufacturers successfully navigating the 510(k) process for autonomous tools [art_general_20250108_005_25b11783].\n4. **Final Approval:** The combination of proven clinical efficacy, market necessity, and a clear regulatory pathway *triggered* the FDA's decision to finally approve the first autonomous AI diagnostic tool for radiologists in late 2025 [art_tech_20260409_009_ac882dfb].\n\n## Countervailing Factors\n- **Professional Association Pushback:** Groups like the American College of Radiology (ACR) expressed serious concerns that autonomous AI was \"not ready for prime time\" due to risks of misdiagnosis and lack of liability clarity [art_health_20250515_011_cb3ec4eb]. \n- **Why they failed:** These concerns were ultimately outweighed by the overwhelming clinical need (radiologist shortage) and the rigorous clinical trial data provided by AI developers that satisfied the FDA's safety and efficacy requirements. The FDA compromised by requiring strict life-cycle management rather than blocking approval.\n\n## Event Candidate Inventory\n- **E1:** FDA denies blanket exemption requests for radiology AI devices\n  - Date: Mid-2025\n  - Why it matters: Ensured that autonomous AI tools would still undergo rigorous 510(k) premarket review, setting the standard for approval.\n  - Source article IDs: [art_general_20250108_005_25b11783]\n- **E2:** FDA clears AI-powered diagnostic tool for autonomous use\n  - Date: Q4 2025\n  - Why it matters: This is the definitive event that resolves the question as True.\n  - Source article IDs: [art_tech_20260409_009_ac882dfb]\n\n## Evidence Mapping Table\n| Claim/Event | Article IDs | Date Support | Confidence (0-1) | Notes |\n|---|---|---|---|---|\n| Surge in AI/ML medical device approvals | [art_general_20250101_005_a4ff6edb] | Early 2025 | 0.9 | Highlights radiology dominance. |\n| FDA maintains rigorous 510(k) for AI | [art_health_20250515_011_cb3ec4eb] | Mid 2025 | 0.9 | Crucial regulatory context. |\n| Final approval of autonomous AI tool | [art_tech_20260409_009_ac882dfb] | Late 2025 | 0.9 | Meets the target criteria. |\n\n## Uncertainties And Alternative Paths\n- **Uncertainty:** The specific liability framework when an autonomous AI makes a diagnostic error remains somewhat ambiguous, even post-approval.\n- **Alternative Path:** Had the professional pushback from radiologist groups been stronger, or if a high-profile clinical trial of an autonomous tool had failed in mid-2025, the FDA might have delayed approvals into 2026.\n",
    "is_polymarket": false,
    "is_overlap": true,
    "market_open": "2025-01-01T00:00:00+00:00",
    "market_open_estimated": false,
    "market_close": "2025-12-31T23:59:59+00:00",
    "polymarket_url": null,
    "price_data": null,
    "events": [
      {
        "id": "evt_tech_20241201_003_c6d6064e",
        "date": "2024-12-01 00:00",
        "title": "Rapid advancement in deep learning and foundation models",
        "description": "Rapid advancement in deep learning and foundation models allowed AI to achieve diagnostic accuracy.",
        "impact": "**Affects:** Yes - Will the FDA approve at least one AI-powered diagn  \n\n**Direction:** Towards outcome    \n\n**Reasoning:**\nImpacts the likelihood of the FDA approving an autonomous AI tool.",
        "has_impact": true,
        "in_market_window": false,
        "source_url": "https://www.yahoo.com/news/articles/philips-secures-fda-clearance-verida-101145432.html",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_health_20241201_006_42622c70",
        "date": "2024-12-01 00:00",
        "title": "Severe shortages of radiologists reported",
        "description": "Severe shortages of radiologists and increased imaging volumes.",
        "impact": "**Affects:** Yes - Will the FDA approve at least one AI-powered diagn  \n\n**Direction:** Towards outcome    \n\n**Reasoning:**\nImpacts the likelihood of the FDA approving an autonomous AI tool.",
        "has_impact": true,
        "in_market_window": false,
        "source_url": "https://www.raps.org/resource/radiologists-to-fda-autonomous-ai-not-ready-for-pr.html",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_politics_20250105_009_0acb95d5",
        "date": "2025-01-05 00:00",
        "title": "FDA denies blanket exemption requests for radiology AI devices",
        "description": "FDA denies blanket exemption requests for radiology AI devices to maintain safety.",
        "impact": "**Affects:** Yes - Will the FDA approve at least one AI-powered diagn  \n\n**Direction:** Towards outcome    \n\n**Reasoning:**\nImpacts the likelihood of the FDA approving an autonomous AI tool.",
        "has_impact": true,
        "in_market_window": false,
        "source_url": "https://www.newswire.ca/news-releases/light-ai-announces-closing-of-over-allotment-option-and-trading-on-cboe-canada-880694900.html",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_health_20250515_001_fa770a0c",
        "date": "2025-05-15 00:00",
        "title": "American College of Radiology expresses concerns over autonomous AI",
        "description": "Professional Association Pushback: Groups like the American College of Radiology (ACR) expressed serious concerns.",
        "impact": "**Affects:** Yes - Will the FDA approve at least one AI-powered diagn  \n\n**Direction:** Against outcome    \n\n**Reasoning:**\nImpacts the likelihood of the FDA approving an autonomous AI tool.",
        "has_impact": true,
        "in_market_window": false,
        "source_url": "https://intuitionlabs.ai/articles/ai-radiology-trends-2025",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_health_20250601_011_ff5f051c",
        "date": "2025-06-01 00:00",
        "title": "AI developers provide rigorous clinical trial data",
        "description": "Rigorous clinical trial data provided by AI developers that satisfied the FDA's safety and efficacy requirements.",
        "impact": "**Affects:** Yes - Will the FDA approve at least one AI-powered diagn  \n\n**Direction:** Towards outcome    \n\n**Reasoning:**\nImpacts the likelihood of the FDA approving an autonomous AI tool.",
        "has_impact": true,
        "in_market_window": false,
        "source_url": "https://link.springer.com/article/10.1007/s00330-026-12460-4",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_tech_20251115_002_c1b69563",
        "date": "2025-11-15 00:00",
        "title": "FDA clears AI-powered diagnostic tool for autonomous use",
        "description": "FDA officially cleared at least one fully autonomous AI diagnostic tool for radiological use.",
        "impact": "**Affects:** Yes - Will the FDA approve at least one AI-powered diagn  \n\n**Direction:** Towards outcome    \n\n**Reasoning:**\nImpacts the likelihood of the FDA approving an autonomous AI tool.",
        "has_impact": true,
        "in_market_window": false,
        "source_url": "https://www.tmcnet.com/usubmit/2026/04/09/10361994.htm",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_tech_20241215_004_6244f6c5",
        "date": "2024-12-15 00:00",
        "title": "AI achieves diagnostic accuracy comparable to human radiologists",
        "description": "AI achieves diagnostic accuracy comparable to or exceeding human radiologists in specific tasks.",
        "impact": "**Affects:** Yes - Will the FDA approve at least one AI-powered diagn  \n\n**Direction:** Towards outcome    \n\n**Reasoning:**\nImpacts the likelihood of the FDA approving an autonomous AI tool.",
        "has_impact": true,
        "in_market_window": false,
        "source_url": "https://www.yahoo.com/news/articles/philips-secures-fda-clearance-verida-101145432.html",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_health_20241215_007_8c2ff1da",
        "date": "2024-12-15 00:00",
        "title": "Massive backlogs and radiologist burnout occur",
        "description": "Massive backlogs and burnout among radiologists.",
        "impact": "**Affects:** Yes - Will the FDA approve at least one AI-powered diagn  \n\n**Direction:** Towards outcome    \n\n**Reasoning:**\nImpacts the likelihood of the FDA approving an autonomous AI tool.",
        "has_impact": true,
        "in_market_window": false,
        "source_url": "https://www.raps.org/resource/radiologists-to-fda-autonomous-ai-not-ready-for-pr.html",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_business_20241220_005_e67f5527",
        "date": "2024-12-20 00:00",
        "title": "Medical device manufacturers increase submissions for autonomous tools",
        "description": "Increased confidence from medical device manufacturers to submit autonomous tools.",
        "impact": "**Affects:** Yes - Will the FDA approve at least one AI-powered diagn  \n\n**Direction:** Towards outcome    \n\n**Reasoning:**\nImpacts the likelihood of the FDA approving an autonomous AI tool.",
        "has_impact": true,
        "in_market_window": false,
        "source_url": "https://www.yahoo.com/news/articles/philips-secures-fda-clearance-verida-101145432.html",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_business_20241220_008_c842b160",
        "date": "2024-12-20 00:00",
        "title": "Strong market demand emerges for autonomous solutions",
        "description": "Strong market demand for autonomous solutions that could operate without constant human oversight.",
        "impact": "**Affects:** Yes - Will the FDA approve at least one AI-powered diagn  \n\n**Direction:** Towards outcome    \n\n**Reasoning:**\nImpacts the likelihood of the FDA approving an autonomous AI tool.",
        "has_impact": true,
        "in_market_window": false,
        "source_url": "https://www.raps.org/resource/radiologists-to-fda-autonomous-ai-not-ready-for-pr.html",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      }
    ]
  },
  {
    "id": "q_health_20251231_058_4faaddb3",
    "title": "Will a new treatment for Alzheimer's disease be approved by the FDA in 2025?",
    "question_type": "binary",
    "options": [
      "Yes",
      "No"
    ],
    "background": "A question about a potential breakthrough in a major area of unmet medical need.",
    "resolution_criteria": "The question will resolve to YES if the FDA grants marketing authorization to a new treatment for Alzheimer's disease in 2025. Otherwise, it will resolve to NO.",
    "outcome": "False",
    "explanation": "\n## Executive Summary\nThe FDA did not approve any new treatments for Alzheimer's disease in 2025 because the most advanced candidates in the pipeline remained in clinical trials or faced setbacks. While the FDA approved updates to existing therapies (like gradual dosing for Eli Lilly's drug) and cleared new diagnostic blood tests, no completely new therapeutic entity achieved regulatory approval. Major pipeline candidates such as Roche's trontinemab and Annovis Bio's buntanetap only progressed to or continued in Phase 3 trials, placing any potential approval beyond the 2025 window. Additionally, companies like Cassava Sciences faced regulatory and clinical hurdles, such as clinical holds, that stalled progress.\n\n## Timeline Of Key Events\n- 2025-02-05: Annovis Bio announced the enrollment of the first patients into its pivotal Phase 3 study for buntanetap in early Alzheimer's disease, confirming the drug would not be ready for 2025 approval [art_general_20250205_008_1e7e1ee1].\n- 2025-04-04: Roche announced the initiation of a Phase 3 study for its Alzheimer's prospect (likely trontinemab) after presenting Phase 2 data, pushing any potential FDA submission well past 2025 [art_general_20250404_025_a6ffedfa].\n- 2025-05-16: The FDA cleared the first blood tests to diagnose and rule out Alzheimer's disease; however, these were diagnostic tools, not new treatments [art_general_20250516_035_41e3fcd7].\n- 2025-07-09: The FDA approved a gradual dosing regimen for Eli Lilly's already-approved Alzheimer's drug, which constituted a label update rather than a new treatment approval [art_general_20250709_030_f5803d9f].\n- 2025-12-19: Cassava Sciences faced a full clinical hold by the FDA on its simufilam epilepsy trial, reflecting broader regulatory hurdles and ongoing scrutiny for the company's pipeline [art_general_20251219_014_0612e9b3].\n\n## Causal Chain Analysis\nThe failure to approve a new Alzheimer's treatment in 2025 was caused by the timing and status of the drug development pipeline. Following the recent approvals of Leqembi (lecanemab) and Kisunla (donanemab) in prior years, the next wave of novel therapeutics (such as trontinemab and buntanetap) was still navigating mid-to-late-stage clinical trials. Because these trials require extended follow-up periods to demonstrate safety and cognitive efficacy, they triggered a natural gap in NDA/BLA submissions. This led to a year where FDA actions were limited to label expansions for existing drugs (like Lilly's gradual dosing) and diagnostic clearances (like blood tests) rather than new approvals [art_general_20250709_030_f5803d9f]. Consequently, this resulted in the negative resolution of the question.\n\n## Countervailing Factors\nThe massive unmet need for Alzheimer's disease and the intense competition among pharmaceutical companies pushed rapid development and significant investment in the space. There was hope that expedited pathways or accelerated approvals could pull some candidates forward. Additionally, positive Phase 2 data from companies like Roche [art_general_20250404_025_a6ffedfa] maintained high momentum. However, these forces failed to overcome the strict timeline requirements for Phase 3 trials and the FDA's rigorous safety standards, especially concerning amyloid-related imaging abnormalities (ARIA).\n\n## Event Candidate Inventory\n- E1\n  - title: Annovis Phase 3 Initiation\n  - date: 2025-02-05\n  - why it matters causally: Confirmed buntanetap was entering Phase 3, ruling out a 2025 approval.\n  - source article IDs: [art_general_20250205_008_1e7e1ee1]\n\n- E2\n  - title: Roche Phase 3 Initiation\n  - date: 2025-04-04\n  - why it matters causally: Confirmed another major pipeline candidate would not finish trials in time for a 2025 approval.\n  - source article IDs: [art_general_20250404_025_a6ffedfa]\n\n- E3\n  - title: FDA Approval of Gradual Dosing for Lilly's Drug\n  - date: 2025-07-09\n  - why it matters causally: Showed FDA activity was focused on existing therapies rather than new ones.\n  - source article IDs: [art_general_20250709_030_f5803d9f]\n\n- E4\n  - title: FDA Clinical Hold on Cassava's Simufilam Trial\n  - date: 2025-12-19\n  - why it matters causally: Highlighted regulatory struggles for secondary pipeline candidates.\n  - source article IDs: [art_general_20251219_014_0612e9b3]\n\n## Evidence Mapping Table\n| Claim/Event | Article IDs | Date Support | Confidence (0-1) | Notes |\n|-------------|-------------|--------------|------------------|-------|\n| Annovis buntanetap enters Phase 3 | [art_general_20250205_008_1e7e1ee1] | 2025-02-05 | 1.0 | Confirms early stage. |\n| Roche starts Phase 3 for Alzheimer's prospect | [art_general_20250404_025_a6ffedfa] | 2025-04-04 | 1.0 | Pushes timeline beyond 2025. |\n| FDA approves gradual dosing for Lilly drug | [art_general_20250709_030_f5803d9f] | 2025-07-09 | 1.0 | Label update, not a new drug. |\n| FDA clears diagnostic blood tests | [art_general_20250516_035_41e3fcd7] | 2025-05-16 | 1.0 | Diagnostic, not therapeutic. |\n| FDA clinical hold on Cassava trial | [art_general_20251219_014_0612e9b3] | 2025-12-19 | 1.0 | Regulatory setback. |\n\n## Uncertainties And Alternative Paths\nThe main uncertainty during 2025 was whether a smaller biotech firm might achieve an unexpected accelerated approval based on biomarker data (such as amyloid clearance) from a Phase 2 trial. Plausible alternative paths included the FDA softening its stance on surrogate endpoints for non-amyloid targets, or a rapid review of an existing drug repurposed for Alzheimer's. However, the FDA's continued strict scrutiny following controversies with previous accelerated approvals ensured no such shortcuts were successful in 2025.\n",
    "is_polymarket": false,
    "is_overlap": true,
    "market_open": "2025-01-01T00:00:00+00:00",
    "market_open_estimated": false,
    "market_close": "2025-12-31T23:59:59+00:00",
    "polymarket_url": null,
    "price_data": null,
    "events": [
      {
        "id": "evt_health_20250205_001_9f9a8e73",
        "date": "2025-02-05 00:00",
        "title": "Annovis Bio Phase 3 Initiation",
        "description": "Annovis Bio announced the enrollment of the first patients into its pivotal Phase 3 study for buntanetap in early Alzheimer's disease.",
        "impact": "**Affects:** No - Will a new treatment for Alzheimer's disease be ap  \n\n**Direction:** Towards outcome    \n\n**Reasoning:**\nThis event hindered the approval of a new treatment, making the NO outcome more likely.",
        "has_impact": true,
        "in_market_window": false,
        "source_url": "https://www.thestar.com/globenewswire/annovis-announces-first-patients-entered-into-pivotal-phase-3-study-of-buntanetap-for-early-alzheimer/article_d85c4c9c-d933-5694-8d0d-b5754a34c57b.html",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_health_20250205_006_c6685aae",
        "date": "2025-02-05 00:00",
        "title": "Buntanetap Timeline Extended",
        "description": "The initiation of Phase 3 trials for buntanetap confirmed the drug would not be ready for 2025 approval.",
        "impact": "**Affects:** No - Will a new treatment for Alzheimer's disease be ap  \n\n**Direction:** Towards outcome    \n\n**Reasoning:**\nThis event hindered the approval of a new treatment, making the NO outcome more likely.",
        "has_impact": true,
        "in_market_window": false,
        "source_url": "https://www.thestar.com/globenewswire/annovis-announces-first-patients-entered-into-pivotal-phase-3-study-of-buntanetap-for-early-alzheimer/article_d85c4c9c-d933-5694-8d0d-b5754a34c57b.html",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_health_20250404_002_0e79ad5f",
        "date": "2025-04-04 00:00",
        "title": "Roche Phase 3 Initiation",
        "description": "Roche announced the initiation of a Phase 3 study for its Alzheimer's prospect (likely trontinemab) after presenting Phase 2 data.",
        "impact": "**Affects:** No - Will a new treatment for Alzheimer's disease be ap  \n\n**Direction:** Towards outcome    \n\n**Reasoning:**\nThis event hindered the approval of a new treatment, making the NO outcome more likely.",
        "has_impact": true,
        "in_market_window": false,
        "source_url": "https://www.benzinga.com/25/04/44652694/roche-plans-to-start-phase-3-study-for-alzheimers-prospect-this-year-presents-new-data-from-phase-2-study",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_health_20250404_007_167654d8",
        "date": "2025-04-04 00:00",
        "title": "Trontinemab Timeline Extended",
        "description": "The initiation of Phase 3 trials for Roche's prospect pushed any potential FDA submission well past 2025.",
        "impact": "**Affects:** No - Will a new treatment for Alzheimer's disease be ap  \n\n**Direction:** Towards outcome    \n\n**Reasoning:**\nThis event hindered the approval of a new treatment, making the NO outcome more likely.",
        "has_impact": true,
        "in_market_window": false,
        "source_url": "https://www.benzinga.com/25/04/44652694/roche-plans-to-start-phase-3-study-for-alzheimers-prospect-this-year-presents-new-data-from-phase-2-study",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_health_20250516_003_3a47256d",
        "date": "2025-05-16 00:00",
        "title": "FDA Clears Diagnostic Blood Tests",
        "description": "The FDA cleared the first blood tests to diagnose and rule out Alzheimer's disease.",
        "impact": "**Affects:** No - Will a new treatment for Alzheimer's disease be ap  \n\n**Direction:** Towards outcome    \n\n**Reasoning:**\nThis event hindered the approval of a new treatment, making the NO outcome more likely.",
        "has_impact": true,
        "in_market_window": false,
        "source_url": "https://www.bloomberg.com/news/articles/2025-05-16/fda-approves-first-blood-test-to-diagnose-alzheimer-s-disease",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_health_20250709_004_0e0368a1",
        "date": "2025-07-09 00:00",
        "title": "FDA Approves Gradual Dosing for Lilly's Drug",
        "description": "The FDA approved a gradual dosing regimen for Eli Lilly's already-approved Alzheimer's drug.",
        "impact": "**Affects:** No - Will a new treatment for Alzheimer's disease be ap  \n\n**Direction:** Towards outcome    \n\n**Reasoning:**\nThis event hindered the approval of a new treatment, making the NO outcome more likely.",
        "has_impact": true,
        "in_market_window": false,
        "source_url": "https://www.dailymail.co.uk/wires/reuters/article-14889153/US-FDA-approves-gradual-dosing-Lilly-Alzheimers-drug.html",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_health_20250709_008_712f7852",
        "date": "2025-07-09 00:00",
        "title": "FDA Focuses on Existing Therapies",
        "description": "FDA actions were limited to label expansions for existing drugs and diagnostic clearances.",
        "impact": "**Affects:** No - Will a new treatment for Alzheimer's disease be ap  \n\n**Direction:** Towards outcome    \n\n**Reasoning:**\nThis event hindered the approval of a new treatment, making the NO outcome more likely.",
        "has_impact": true,
        "in_market_window": false,
        "source_url": "https://www.dailymail.co.uk/wires/reuters/article-14889153/US-FDA-approves-gradual-dosing-Lilly-Alzheimers-drug.html",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_health_20251219_005_0c647942",
        "date": "2025-12-19 00:00",
        "title": "FDA Clinical Hold on Cassava's Simufilam Trial",
        "description": "Cassava Sciences faced a full clinical hold by the FDA on its simufilam epilepsy trial.",
        "impact": "**Affects:** No - Will a new treatment for Alzheimer's disease be ap  \n\n**Direction:** Towards outcome    \n\n**Reasoning:**\nThis event hindered the approval of a new treatment, making the NO outcome more likely.",
        "has_impact": true,
        "in_market_window": false,
        "source_url": "https://www.benzinga.com/news/fda/25/12/49512032/fda-puts-cassavas-simufilam-epilepsy-trial-on-full-clinical-hold",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_health_20251219_009_bae69078",
        "date": "2025-12-19 00:00",
        "title": "Regulatory Hurdles for Secondary Candidates",
        "description": "Clinical holds highlighted regulatory struggles for secondary pipeline candidates.",
        "impact": "**Affects:** No - Will a new treatment for Alzheimer's disease be ap  \n\n**Direction:** Towards outcome    \n\n**Reasoning:**\nThis event hindered the approval of a new treatment, making the NO outcome more likely.",
        "has_impact": true,
        "in_market_window": false,
        "source_url": "https://www.benzinga.com/news/fda/25/12/49512032/fda-puts-cassavas-simufilam-epilepsy-trial-on-full-clinical-hold",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_health_20251219_010_8089acdc",
        "date": "2025-12-19 00:00",
        "title": "No New Alzheimer's Treatment Approved in 2025",
        "description": "The FDA did not approve any new treatments for Alzheimer's disease in 2025.",
        "impact": "**Affects:** No - Will a new treatment for Alzheimer's disease be ap  \n\n**Direction:** Towards outcome    \n\n**Reasoning:**\nThis event hindered the approval of a new treatment, making the NO outcome more likely.",
        "has_impact": true,
        "in_market_window": false,
        "source_url": "https://www.benzinga.com/news/fda/25/12/49512032/fda-puts-cassavas-simufilam-epilepsy-trial-on-full-clinical-hold",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      }
    ]
  }
];