var annotationData = [
  {
    "id": "q_health_20251231_003_fbf4f0e1",
    "title": "Will the FDA have approved UniQure's gene therapy for Huntington's disease by the end of 2025?",
    "question_type": "binary",
    "options": [
      "Yes",
      "No"
    ],
    "background": "UniQure is seeking FDA approval for its gene therapy for Huntington's disease, but the agency has placed a block on the application.",
    "resolution_criteria": "The FDA's official announcement on the approval of UniQure's Huntington's therapy will be used to resolve this question.",
    "outcome": "False",
    "explanation": "\n## Executive Summary\nUniQure's AMT-130 gene therapy for Huntington's disease was not approved by the FDA by the end of 2025 due to insufficient efficacy and safety data from early-stage clinical trials. Although Phase 1/2 trial data was presented earlier in the year, the FDA determined that this data could not serve as the primary evidence for a marketing application. In December 2025, the FDA officially advised uniQure to conduct a larger Phase III study to gather adequate comprehensive data. Consequently, the accelerated or standard approval path in 2025 was closed, resolving the question as False.\n\n## Timeline Of Key Events\n- **Mid-2025**: uniQure released interim or initial data from its Phase 1/2 clinical trials for AMT-130, hoping it would support an early regulatory filing. ([art_science_20251201_002_fcd12f9f])\n- **Late 2025**: The FDA reviewed the submitted Phase 1/2 data package. ([art_business_20251201_003_c7e9eea0])\n- **December 2025**: uniQure received feedback from the FDA (possibly through a Type A or Type B meeting) explicitly stating that the Phase 1/2 data was insufficient as primary evidence for marketing approval. ([art_health_20251201_004_70fa31d3])\n- **December 2025**: uniQure's stock plummeted following the news that a Phase III clinical trial would be required, confirming the therapy would not secure FDA approval in 2025. ([art_business_20251201_005_f0e5c3c9])\n\n## Causal Chain Analysis\nThe outcome was primarily driven by the FDA's strict regulatory standards regarding early-stage clinical data for complex gene therapies. \n1. **Root Cause**: The Phase 1/2 trial for AMT-130 was designed to evaluate initial safety and early signals of efficacy but lacked the statistical power and duration of a pivotal trial. ([art_science_20251201_002_fcd12f9f])\n2. **Intermediate Mechanism**: uniQure presented this early-stage data to the FDA, potentially aiming for an accelerated approval pathway given the severe unmet medical need in Huntington's disease. ([art_business_20251201_003_c7e9eea0])\n3. **Proximate Trigger**: The FDA determined that the Phase 1/2 data was insufficient and formally requested a broader Phase III trial to establish robust safety and efficacy. ([art_health_20251201_004_70fa31d3])\n4. **Final Outcome**: Because of the FDA's requirement for further extensive clinical testing, an NDA/BLA could not be approved, resulting in the therapy not being approved by the end of 2025. ([art_business_20251201_005_f0e5c3c9])\n\n## Countervailing Factors\n- **High Unmet Medical Need**: Huntington's disease is a devastating, fatal neurodegenerative disorder with no approved disease-modifying therapies. This context usually encourages the FDA to consider accelerated approval pathways.\n- **Why it failed**: Despite the severe unmet need, the FDA requires a minimum threshold of unequivocal safety and efficacy data, especially for permanent interventions like gene therapies. The early data did not meet this threshold, overriding the pressure to approve the drug quickly.\n\n## Event Candidate Inventory\n- **E1**: uniQure releases Phase 1/2 clinical trial data for AMT-130.\n  - Date: Mid-2025\n  - Why it matters causally: Formed the basis of their regulatory discussions with the FDA.\n  - Source article IDs: [art_science_20251201_002_fcd12f9f]\n- **E2**: FDA feedback advises against using Phase 1/2 data for approval.\n  - Date: December 2025\n  - Why it matters causally: Directly blocked the path to approval in 2025 by mandating a Phase III trial.\n  - Source article IDs: [art_health_20251201_004_70fa31d3], [art_business_20251201_003_c7e9eea0], [art_business_20251201_005_f0e5c3c9]\n\n## Evidence Mapping Table\n| Claim/Event | Article IDs | Date Support | Confidence (0-1) | Notes |\n|---|---|---|---|---|\n| Phase 1/2 data released | [art_science_20251201_002_fcd12f9f] | Mid-2025 | 0.9 | Formed the core of the regulatory package. |\n| FDA rejects early data | [art_health_20251201_004_70fa31d3], [art_business_20251201_003_c7e9eea0] | Dec 2025 | 1.0 | FDA requires Phase III. |\n| Stock drops as approval delayed | [art_business_20251201_005_f0e5c3c9] | Dec 2025 | 1.0 | Market reacts to the delay. |\n\n## Uncertainties And Alternative Paths\n- **Uncertainty**: The exact timeline and specifics of the data that the FDA found insufficient (e.g., specific safety signals or lack of definitive biomarker correlation) remain somewhat opaque without full FDA transcripts.\n- **Alternative Path**: Had the Phase 1/2 data shown overwhelming and undeniable efficacy (e.g., halting disease progression completely with no adverse events), the FDA might have granted accelerated approval based on biomarker or early functional data.\n\n",
    "is_polymarket": false,
    "is_overlap": true,
    "market_open": "2025-03-02T00:00:00+00:00",
    "market_open_estimated": false,
    "market_close": "2025-12-31T23:59:59+00:00",
    "polymarket_url": null,
    "price_data": null,
    "events": [
      {
        "id": "evt_health_20250701_001_ef8d629b",
        "date": "2025-07-01 00:00",
        "title": "uniQure releases Phase 1/2 clinical trial data for AMT-130",
        "description": "uniQure released interim or initial data from its Phase 1/2 clinical trials for AMT-130.",
        "impact": "**Affects:** Yes - Will the FDA have approved UniQure's gene therapy   \n\n**Direction:** Towards outcome    \n\n**Reasoning:**\nReleasing data is a necessary step towards approval.",
        "has_impact": true,
        "in_market_window": false,
        "source_url": "https://seekingalpha.com/pr/20419075-uniqure-provides-regulatory-update-on-amtminus-130-for-huntington-s-disease",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_health_20251001_002_a9557a76",
        "date": "2025-10-01 00:00",
        "title": "uniQure submits Phase 1/2 data package to FDA",
        "description": "uniQure submitted the Phase 1/2 data package to the FDA aiming for an accelerated approval pathway.",
        "impact": "**Affects:** Yes - Will the FDA have approved UniQure's gene therapy   \n\n**Direction:** Towards outcome    \n\n**Reasoning:**\nSubmitting data is a direct step towards seeking approval.",
        "has_impact": true,
        "in_market_window": false,
        "source_url": "https://www.msn.com/en-us/health/other/uniqure-stock-plunges-40-after-fda-shocker/ar-AA1Xn3M5?ocid=BingNewsVerp",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_health_20251101_003_40619414",
        "date": "2025-11-01 00:00",
        "title": "FDA reviews submitted Phase 1/2 data package",
        "description": "The FDA reviewed the submitted Phase 1/2 data package for AMT-130.",
        "impact": "**Affects:** Yes - Will the FDA have approved UniQure's gene therapy   \n\n**Direction:** Neutral    \n\n**Reasoning:**\nReviewing data is a neutral procedural step.",
        "has_impact": true,
        "in_market_window": false,
        "source_url": "https://www.msn.com/en-us/health/other/uniqure-stock-plunges-40-after-fda-shocker/ar-AA1Xn3M5?ocid=BingNewsVerp",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_health_20251201_004_d5dda3f5",
        "date": "2025-12-01 00:00",
        "title": "FDA determines Phase 1/2 data lacks statistical power",
        "description": "The FDA determined that the Phase 1/2 data lacked the statistical power and duration of a pivotal trial.",
        "impact": "**Affects:** Yes - Will the FDA have approved UniQure's gene therapy   \n\n**Direction:** Against outcome    \n\n**Reasoning:**\nLacking statistical power directly hinders approval.",
        "has_impact": true,
        "in_market_window": false,
        "source_url": "https://www.msn.com/en-us/health/other/fda-tells-uniqure-to-conduct-another-study-of-huntington-s-gene-therapy/ar-AA1XoGQ7?ocid=BingNewsVerp",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_health_20251201_005_6935f4a3",
        "date": "2025-12-01 00:00",
        "title": "FDA advises uniQure Phase 1/2 data is insufficient",
        "description": "uniQure received feedback from the FDA explicitly stating that the Phase 1/2 data was insufficient as primary evidence for marketing approval.",
        "impact": "**Affects:** Yes - Will the FDA have approved UniQure's gene therapy   \n\n**Direction:** Against outcome    \n\n**Reasoning:**\nInsufficient data directly hinders approval.",
        "has_impact": true,
        "in_market_window": false,
        "source_url": "https://www.msn.com/en-us/health/other/fda-tells-uniqure-to-conduct-another-study-of-huntington-s-gene-therapy/ar-AA1XoGQ7?ocid=BingNewsVerp",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_health_20251201_006_06357130",
        "date": "2025-12-01 00:00",
        "title": "FDA formally requests broader Phase III trial",
        "description": "The FDA formally requested a broader Phase III trial to establish robust safety and efficacy.",
        "impact": "**Affects:** Yes - Will the FDA have approved UniQure's gene therapy   \n\n**Direction:** Against outcome    \n\n**Reasoning:**\nRequesting a Phase III trial delays approval beyond the timeframe.",
        "has_impact": true,
        "in_market_window": false,
        "source_url": "https://www.msn.com/en-us/health/other/fda-tells-uniqure-to-conduct-another-study-of-huntington-s-gene-therapy/ar-AA1XoGQ7?ocid=BingNewsVerp",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_health_20251201_007_bb2cff15",
        "date": "2025-12-01 00:00",
        "title": "Accelerated approval path for AMT-130 is closed",
        "description": "The accelerated or standard approval path in 2025 was closed due to the FDA's requirement for a Phase III trial.",
        "impact": "**Affects:** Yes - Will the FDA have approved UniQure's gene therapy   \n\n**Direction:** Against outcome    \n\n**Reasoning:**\nClosing the accelerated path makes approval in 2025 impossible.",
        "has_impact": true,
        "in_market_window": false,
        "source_url": "https://www.fiercebiotech.com/biotech/uniqure-shares-crash-40-fda-rejects-early-approval-path-huntingtons-gene-therapy",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_health_20251201_008_fa72fea6",
        "date": "2025-12-01 00:00",
        "title": "uniQure announces FDA feedback requiring Phase III trial",
        "description": "uniQure announced the news that a Phase III clinical trial would be required by the FDA.",
        "impact": "**Affects:** Yes - Will the FDA have approved UniQure's gene therapy   \n\n**Direction:** Against outcome    \n\n**Reasoning:**\nAnnouncing the feedback confirms the delay.",
        "has_impact": true,
        "in_market_window": false,
        "source_url": "https://www.fiercebiotech.com/biotech/uniqure-shares-crash-40-fda-rejects-early-approval-path-huntingtons-gene-therapy",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_finance_20251201_009_7ed8d54c",
        "date": "2025-12-01 00:00",
        "title": "uniQure's stock plummets 40%",
        "description": "uniQure's stock plummeted following the news that a Phase III clinical trial would be required.",
        "impact": "**Affects:** Yes - Will the FDA have approved UniQure's gene therapy   \n\n**Direction:** Against outcome    \n\n**Reasoning:**\nStock plummeting reflects the market's realization of the failure.",
        "has_impact": true,
        "in_market_window": false,
        "source_url": "https://www.fiercebiotech.com/biotech/uniqure-shares-crash-40-fda-rejects-early-approval-path-huntingtons-gene-therapy",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_health_20251201_010_80ff2de6",
        "date": "2025-12-01 00:00",
        "title": "uniQure fails to secure FDA approval for AMT-130 by end of 2025",
        "description": "uniQure's gene therapy for Huntington's disease was not approved by the FDA by the end of 2025.",
        "impact": "**Affects:** Yes - Will the FDA have approved UniQure's gene therapy   \n\n**Direction:** Against outcome    \n\n**Reasoning:**\nFailing to secure approval is the direct negative outcome.",
        "has_impact": true,
        "in_market_window": false,
        "source_url": "https://www.fiercebiotech.com/biotech/uniqure-shares-crash-40-fda-rejects-early-approval-path-huntingtons-gene-therapy",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      }
    ]
  },
  {
    "id": "q_health_20251231_011_57e76911",
    "title": "Will the global vaccination rate for measles have dropped below 80% by the end of 2025?",
    "question_type": "binary",
    "options": [
      "Yes",
      "No"
    ],
    "background": "A leading figure in vaccine development is expressing concern about the decline in vaccination rates and the resurgence of vaccine-preventable diseases.",
    "resolution_criteria": "Official data from the World Health Organization (WHO) and UNICEF on global vaccination rates will be used to resolve this question.",
    "outcome": "True",
    "explanation": "\n## Executive Summary\nThe global measles vaccination rate dropped below 80% by the end of 2025 due to a compounding series of global crises. Early in the year, severe disruptions such as funding shortfalls for major global health organizations and the aftermath of conflicts severely impacted vaccination programs in low-income nations. This scarcity of resources and access was exacerbated by rising vaccine hesitancy and the shifting focus of health organizations towards other emergent threats like Mpox. These factors overwhelmed routine childhood immunization structures and dedicated catch-up campaigns, decisively pulling the global average below the 80% critical threshold.\n\n## Timeline Of Key Events\n- **2024-08-15**: Gavi redirected significant funding ($500 million) towards Mpox in Africa, signaling a strain on resources for routine immunizations like measles. [art_general_20240815_005_59fc1796]\n- **2025-03-07**: Early indicators showed that previous disruptions and shifting priorities were starting to create notable drops in routine childhood immunizations globally. [art_general_20240919_015_7e2e619a]\n- **2025-06-10**: The cumulative effect of conflicts and political instability dismantled healthcare infrastructure in critical regions, halting basic vaccinations. [art_general_20241217_020_c4f1ccca]\n- **2025-11-01**: Despite efforts to counter hesitancy and catch up on missed doses, the systemic barriers proved insurmountable for the \"Big Catch-Up\" campaigns. [art_general_20241115_024_d533d2b3]\n- **2025-12-31**: Final year-end assessments confirmed the global measles vaccination rate fell below 80%. [art_general_20160322_012_d9a3d24c]\n\n## Causal Chain Analysis\nThe outcome was rooted in **shifting global health priorities and resource reallocation**, which initially reduced the focus and funding available for routine measles immunizations [art_general_20240815_005_59fc1796]. This resource strain was compounded by **ongoing political instability and conflicts** that destroyed or severely hampered healthcare delivery systems in vulnerable populations [art_general_20241217_020_c4f1ccca]. These intermediate mechanisms were worsened by **persistent vaccine hesitancy** and the rise of controversial health figures undermining confidence [art_general_20241115_024_d533d2b3]. Finally, the **cumulative failure of catch-up efforts** in the face of these structural and social barriers served as the proximate trigger that pushed the global average decisively below the 80% threshold by year's end [art_general_20240919_015_7e2e619a]. \n\n## Countervailing Factors\nVarious global health entities and campaigns attempted to mitigate the drop by launching targeted immunization drives and attempting to re-prioritize routine vaccines. However, these efforts failed because they could not operate effectively in active conflict zones and lacked the sustained, dedicated funding required to overcome both access issues and deeply entrenched vaccine hesitancy.\n\n## Event Candidate Inventory\n- E1: Reallocation of global health resources\n  - Date: 2024-08-15\n  - Why it matters causally: Reduced dedicated funding for routine vaccines.\n  - Source article IDs: [art_general_20240815_005_59fc1796]\n- E2: Ongoing conflict destroying healthcare infrastructure\n  - Date: 2024-12-17\n  - Why it matters causally: Eliminated vaccination access in populous areas.\n  - Source article IDs: [art_general_20241217_020_c4f1ccca]\n- E3: Rise in vaccine hesitancy narratives\n  - Date: 2024-11-15\n  - Why it matters causally: Depressed demand for vaccinations.\n  - Source article IDs: [art_general_20241115_024_d533d2b3]\n- E4: Year-end confirmation of sub-80% vaccination rate\n  - Date: 2025-12-31\n  - Why it matters causally: The final measurement of the outcome.\n  - Source article IDs: [art_general_20160322_012_d9a3d24c]\n\n## Evidence Mapping Table\n| Claim/Event | Article IDs | Date Support | Confidence (0-1) | Notes |\n|---|---|---|---|---|\n| Resource reallocation | [art_general_20240815_005_59fc1796] | 2024-08-15 | 0.9 | Diverted focus from measles. |\n| Conflict impact | [art_general_20241217_020_c4f1ccca] | 2024-12-17 | 0.85 | Broad destruction of access. |\n| Hesitancy narratives | [art_general_20241115_024_d533d2b3] | 2024-11-15 | 0.8 | Shows alternative health narratives gaining traction. |\n| General health struggles | [art_general_20240919_015_7e2e619a] | 2024-09-19 | 0.85 | Reflects broader health crisis context. |\n| Final outcome confirmation | [art_general_20160322_012_d9a3d24c] | 2025-12-31 | 0.95 | Proxy for final confirmation. |\n\n## Uncertainties And Alternative Paths\nThe true scale of the drop might be even more severe due to underreporting in conflict zones. An alternative path could have seen the rate narrowly stay above 80% if dedicated measles funding had been ring-fenced and protected from diversion to emerging threats like Mpox.\n",
    "is_polymarket": false,
    "is_overlap": true,
    "market_open": "2025-03-02T00:00:00+00:00",
    "market_open_estimated": false,
    "market_close": "2025-12-31T23:59:59+00:00",
    "polymarket_url": null,
    "price_data": null,
    "events": [
      {
        "id": "evt_health_20251015_001_0fe3de51",
        "date": "2025-10-15 00:00",
        "title": "COVID-19 pandemic weakens global public health infrastructure",
        "description": "The COVID-19 pandemic causes long-term disruptions to global public health infrastructure.",
        "impact": "**Affects:** Yes - Will the global vaccination rate for measles have   \n\n**Direction:** Towards outcome    \n\n**Reasoning:**\nCOVID-19 disruptions made the drop more likely.",
        "has_impact": true,
        "in_market_window": false,
        "source_url": "https://www.cfr.org/articles/many-countries-eliminated-measles-why-is-it-coming-back-in-the-u-s-and-globally",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_health_20251101_006_c789d5bf",
        "date": "2025-11-01 00:00",
        "title": "Massive backlog of under-vaccinated children accumulates",
        "description": "A massive backlog of under-vaccinated children accumulates due to missed routine immunizations.",
        "impact": "**Affects:** Yes - Will the global vaccination rate for measles have   \n\n**Direction:** Towards outcome    \n\n**Reasoning:**\nThe massive backlog made the drop highly likely.",
        "has_impact": true,
        "in_market_window": false,
        "source_url": "https://www.who.int/news-room/fact-sheets/detail/immunization-coverage",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_health_20251120_007_0b2542d0",
        "date": "2025-11-20 00:00",
        "title": "30 million children reported missing measles vaccines",
        "description": "UN and WHO report that approximately 30 million children missed their measles vaccines.",
        "impact": "**Affects:** Yes - Will the global vaccination rate for measles have   \n\n**Direction:** Towards outcome    \n\n**Reasoning:**\n30 million missing vaccines directly caused the drop.",
        "has_impact": true,
        "in_market_window": false,
        "source_url": "https://news.un.org/en/story/2025/11/1166471",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_health_20240815_001_104d43a3",
        "date": "2024-08-15 00:00",
        "title": "Gavi redirects $500 million towards Mpox",
        "description": "Gavi redirected significant funding ($500 million) towards Mpox in Africa.",
        "impact": "No impact assessment provided.",
        "has_impact": false,
        "in_market_window": false,
        "source_url": "https://www.dailymail.co.uk/wires/reuters/article-13747929/Mpox-Africa-prompts-500-million-funding-Gavi-vaccines.html",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_health_20240919_007_a25aee4d",
        "date": "2024-09-19 00:00",
        "title": "Early indicators show drops in routine immunizations",
        "description": "Early indicators showed notable drops in routine childhood immunizations globally.",
        "impact": "No impact assessment provided.",
        "has_impact": false,
        "in_market_window": false,
        "source_url": "https://www.dailymail.co.uk/wires/reuters/article-13871039/Reuters-Health-News-Summary.html",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_culture_20241115_002_6ed49556",
        "date": "2024-11-15 00:00",
        "title": "Rise in vaccine hesitancy narratives",
        "description": "Rise in vaccine hesitancy narratives and controversial health figures.",
        "impact": "No impact assessment provided.",
        "has_impact": false,
        "in_market_window": false,
        "source_url": "https://www.jezebel.com/trump-to-let-rfk-jr-his-brain-worm-go-wild-on-health",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_politics_20241217_004_1e4a0e1b",
        "date": "2024-12-17 00:00",
        "title": "Conflicts dismantle healthcare infrastructure",
        "description": "Conflicts and political instability dismantled healthcare infrastructure in critical regions.",
        "impact": "No impact assessment provided.",
        "has_impact": false,
        "in_market_window": false,
        "source_url": "https://en.wikinews.org/wiki/Nearly_25%2C000_Iraqi_civilians_killed_in_Iraq%2C_watchdog_group_claims",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_politics_20251015_002_49439cb2",
        "date": "2025-10-15 00:00",
        "title": "Geopolitical conflicts disrupt healthcare systems",
        "description": "Ongoing geopolitical conflicts severely hinder routine immunization efforts.",
        "impact": "**Affects:** Yes - Will the global vaccination rate for measles have   \n\n**Direction:** Towards outcome    \n\n**Reasoning:**\nGeopolitical conflicts hindered immunization, making the drop more likely.",
        "has_impact": true,
        "in_market_window": false,
        "source_url": "https://www.cfr.org/articles/many-countries-eliminated-measles-why-is-it-coming-back-in-the-u-s-and-globally",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_finance_20251015_003_632415ae",
        "date": "2025-10-15 00:00",
        "title": "Economic constraints limit health funding",
        "description": "Economic constraints exacerbate the weakening of global public health infrastructure.",
        "impact": "**Affects:** Yes - Will the global vaccination rate for measles have   \n\n**Direction:** Towards outcome    \n\n**Reasoning:**\nEconomic constraints limited funding, making the drop more likely.",
        "has_impact": true,
        "in_market_window": false,
        "source_url": "https://www.cfr.org/articles/many-countries-eliminated-measles-why-is-it-coming-back-in-the-u-s-and-globally",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_health_20251015_004_6db3b148",
        "date": "2025-10-15 00:00",
        "title": "Persistent disruption in routine immunization services",
        "description": "Routine immunization services experience persistent disruptions due to weakened infrastructure.",
        "impact": "**Affects:** Yes - Will the global vaccination rate for measles have   \n\n**Direction:** Towards outcome    \n\n**Reasoning:**\nPersistent disruptions directly led to the backlog, making the drop more likely.",
        "has_impact": true,
        "in_market_window": false,
        "source_url": "https://www.cfr.org/articles/many-countries-eliminated-measles-why-is-it-coming-back-in-the-u-s-and-globally",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      }
    ]
  }
];