var annotationData = [
  {
    "id": "polymarket_event_225893",
    "title": "PGA Tour: Cognizant Classic in The Palm Beaches Winner",
    "question_type": "mcq",
    "options": [
      "Daniel Brown",
      "Rafael Campos",
      "Luke Clanton",
      "Ze-Cheng Dou",
      "Adrien Dumont De Chassart",
      "Justin Hicks",
      "Rico Hoey",
      "Charley Hoffman",
      "Nicolai Hojgaard",
      "Beau Hossler",
      "Mark Hubbard",
      "Mackenzie Hughes",
      "Stephan Jaeger",
      "Seong-Hyeon Kim",
      "Christo Lamprecht",
      "Henry Lebioda",
      "Kyoung-Hoon Lee",
      "Hao-Tong Li",
      "David Lipsky",
      "Justin Lower",
      "Shane Lowry",
      "Peter Malnati",
      "Max McGreevy",
      "Matthieu Pavon",
      "Taylor Pendrith",
      "Chandler Phillips",
      "Seamus Power",
      "Andrew Putnam",
      "Aaron Rai",
      "Kevin Roy",
      "Marcelo Rozo",
      "Adrien Saddier",
      "Isaiah Salinda",
      "Gordon Sargent",
      "Adam Schenk",
      "Zach Bauchou",
      "Christiaan Bezuidenhout",
      "Chandler Blanchet",
      "Blades Brown",
      "Eric Cole",
      "A.J. Ewart",
      "Joel Dahmen",
      "Cam Davis",
      "Nick Dunlap",
      "Nicolas Echavarria",
      "Austin Eckroat",
      "Doug Ghim",
      "Ben Griffin",
      "Emiliano Grillo",
      "Tom Kim",
      "Chris Kirk",
      "Patton Kizzire",
      "Brooks Koepka",
      "Matt Kuchar",
      "Mac Meissner",
      "Keith Mitchell",
      "Taylor Moore",
      "William Mouw",
      "Michael Brennan",
      "Jacob Bridgeman",
      "Ricky Castillo",
      "Davis Chatfield",
      "Patrick Fishburn",
      "Steven Fisk",
      "David Ford",
      "Brice Garnett",
      "Ryan Gerard",
      "Garrick Higgo",
      "Joe Highsmith",
      "Kensei Hirata",
      "Lee Hodges",
      "Rasmus Hojgaard",
      "Max Homa",
      "Billy Horschel",
      "Takumi Kanaya",
      "Jeffrey Kang",
      "Johnny Keefer",
      "Michael Kim",
      "Keita Nakajima",
      "Rasmus Neergaard-Petersen",
      "Pontus Nyholm",
      "Thorbjorn Olesen",
      "John Parry",
      "Chad Ramey",
      "Kristoffer Reitan",
      "Davis Riley",
      "Patrick Rodgers",
      "Matthias Schmid",
      "Adam Scott",
      "Neal Shipley",
      "Webb Simpson",
      "Alex Smalley",
      "Jordan L. Smith",
      "Austin Smotherman",
      "Jimmy Stanger",
      "Kevin Streelman",
      "Adam Svensson",
      "Jesper Svensson",
      "Davis Thompson",
      "Michael Thorbjornsen"
    ],
    "background": "No background available.",
    "resolution_criteria": "This market will resolve according to the listed player who wins the 2026 Cognizant Classic in The Palm Beaches tournament.\n\nIf a listed player is eliminated from contention for the Cognizant Classic in The Palm Beaches tournament based on the official rules of the tournament, the relevant market will immediately resolve to \"No\".\n\nIf an unlisted player wins the Cognizant Classic in The Palm Beaches tournament this market will resolve to \"Other\".\n\nIn the event of a tie, this market will resolve according to the official winner as determined by PGA Tour official tournament rules. If multiple winners are announced then this market will resolve to the player whose listed last name comes first alphabetically.\n\nIf no winner is announced by March 7, 2026 at 7:00PM ET this market will resolve to \"Other\".\n\nThe primary resolution source will be the official results published by the PGA Tour website (https://www.pgatour.com/).",
    "outcome": "Nicolas Echavarria",
    "explanation": "\n## Executive Summary\nNicolas Echavarria secured his third PGA Tour victory at the 2026 Cognizant Classic in The Palm Beaches through a combination of flawless weekend play and a late collapse by his main competitor. Echavarria shot a 5-under 66 on Sunday to finish at 17-under 267, playing the entire weekend without a single bogey. The outcome was decisively shaped by Shane Lowry, who held a three-shot lead on the 16th tee but suffered consecutive double bogeys, opening the door for Echavarria to claim the title and the $1,728,000 top prize.\n\n## Timeline Of Key Events\n- March 1, 2026: Nicolas Echavarria continues a bogey-free streak entering the final round. Shane Lowry holds a commanding lead heading into the final stretch. [art_general_20260302_006_afecb454]\n- March 1, 2026 (Late Round): On the 16th tee, Lowry holds a three-shot lead. [art_general_20260302_006_afecb454]\n- March 1, 2026 (Hole 16 & 17): Lowry makes consecutive double bogeys, losing his lead. [art_general_20260302_006_afecb454]\n- March 1, 2026 (Conclusion): Echavarria completes his final round of 5-under 66 to finish at 17-under 267, clinching the victory. [art_general_20260302_006_afecb454]\n\n## Causal Chain Analysis\nThe primary cause of the outcome was a combination of Echavarria's steady play and Lowry's late-round mistakes. Echavarria's flawless weekend performance kept him within striking distance [art_general_20260302_006_afecb454]. The critical proximate trigger was Shane Lowry's collapse on holes 16 and 17, where he recorded consecutive double bogeys [art_general_20260302_006_afecb454]. This sudden drop in performance directly resulted in Echavarria taking the lead and ultimately winning the tournament.\n\n## Countervailing Factors\nThe main countervailing factor was Shane Lowry's dominant position for most of the tournament. Up until the 16th hole of the final round, Lowry seemed poised to win. However, his performance collapsed under pressure or difficult course conditions (PGA National's \"Bear Trap\"), overwhelming his earlier advantage [art_general_20260302_006_afecb454].\n\n## Event Candidate Inventory\n- E1: Echavarria's Flawless Weekend\n  - Date: Feb 28 - March 1, 2026\n  - Why it matters causally: Kept him in contention and applied pressure to the leader.\n  - Source article IDs: [art_general_20260302_006_afecb454]\n\n- E2: Lowry's Collapse\n  - Date: March 1, 2026\n  - Why it matters causally: Direct cause of the lead change.\n  - Source article IDs: [art_general_20260302_006_afecb454]\n\n## Evidence Mapping Table\n| Claim/Event | Article IDs | Date Support | Confidence (0-1) | Notes |\n|---|---|---|---|---|\n| Echavarria's win | art_general_20260302_006_afecb454 | March 1, 2026 | 0.9 | Based on evidence collector summary |\n| Lowry's double bogeys | art_general_20260302_006_afecb454 | March 1, 2026 | 0.9 | Based on evidence collector summary |\n\n## Uncertainties And Alternative Paths\n- If Lowry had parred the 16th and 17th holes, he would have likely won.\n- It is uncertain if other competitors were close enough to challenge Echavarria if Lowry had not collapsed. [art_general_20260302_006_afecb454]\n",
    "is_polymarket": true,
    "is_overlap": false,
    "market_open": "2025-12-02T03:08:35+00:00",
    "market_open_estimated": true,
    "market_close": "2026-03-02T03:08:35+00:00",
    "polymarket_url": "https://polymarket.com/event/2026-cognizant-classic-in-the-palm-beaches-winner",
    "price_data": {
      "history": [
        {
          "t": 1771977635,
          "p": 0.215
        },
        {
          "t": 1772020839,
          "p": 0.0065
        },
        {
          "t": 1772064032,
          "p": 0.006
        },
        {
          "t": 1772107245,
          "p": 0.4455
        },
        {
          "t": 1772150436,
          "p": 0.01
        },
        {
          "t": 1772193650,
          "p": 0.1805
        },
        {
          "t": 1772236837,
          "p": 0.3345
        },
        {
          "t": 1772280056,
          "p": 0.24
        },
        {
          "t": 1772323247,
          "p": 0.1065
        },
        {
          "t": 1772366440,
          "p": 0.0815
        },
        {
          "t": 1772409648,
          "p": 0.0005
        }
      ],
      "turning_points": [
        {
          "t": 1772020839,
          "p": 0.0065,
          "delta": -0.2085
        },
        {
          "t": 1772107245,
          "p": 0.4455,
          "delta": 0.439
        },
        {
          "t": 1772150436,
          "p": 0.01,
          "delta": -0.4355
        },
        {
          "t": 1772193650,
          "p": 0.1805,
          "delta": 0.1705
        },
        {
          "t": 1772236837,
          "p": 0.3345,
          "delta": 0.154
        },
        {
          "t": 1772280056,
          "p": 0.24,
          "delta": -0.0945
        },
        {
          "t": 1772323247,
          "p": 0.1065,
          "delta": -0.1335
        },
        {
          "t": 1772409648,
          "p": 0.0005,
          "delta": -0.106
        }
      ],
      "price_at_open": null,
      "price_at_close": 0.0005,
      "min_price": 0.0005,
      "max_price": 0.4455,
      "final_price": 0.0005,
      "fetched_at": "2026-04-20T17:08:23.586094+00:00"
    },
    "events": [
      {
        "id": "evt_sports_20260301_001_1a7b612b",
        "date": "2026-03-01 00:00",
        "title": "Echavarria plays a flawless weekend",
        "description": "Nicolas Echavarria plays a flawless weekend, keeping him in contention.",
        "impact": "**Affects:** Option 45: Nicolas Echavarria  \n\n**Direction:** Towards outcome    \n\n**Reasoning:**\nThis event contributed to Nicolas Echavarria winning the tournament.",
        "has_impact": true,
        "in_market_window": true,
        "source_url": "https://www.heraldmailmedia.com/story/sports/golf/pga/2026/03/01/nico-echavarria-wins-cognizant-classic-2026/88937027007",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_sports_20260301_002_4481efd0",
        "date": "2026-03-01 15:00",
        "title": "Lowry holds a three-shot lead on the 16th tee",
        "description": "Shane Lowry holds a three-shot lead on the 16th tee during the final round.",
        "impact": "**Affects:** Option 45: Nicolas Echavarria  \n\n**Direction:** Towards outcome    \n\n**Reasoning:**\nThis event contributed to Nicolas Echavarria winning the tournament.",
        "has_impact": true,
        "in_market_window": true,
        "source_url": "https://www.heraldmailmedia.com/story/sports/golf/pga/2026/03/01/nico-echavarria-wins-cognizant-classic-2026/88937027007",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_sports_20260301_003_10488ab8",
        "date": "2026-03-01 15:10",
        "title": "Lowry hits a woeful iron shot on hole 16",
        "description": "Shane Lowry hits a woeful iron shot on hole 16.",
        "impact": "**Affects:** Option 45: Nicolas Echavarria  \n\n**Direction:** Towards outcome    \n\n**Reasoning:**\nThis event contributed to Nicolas Echavarria winning the tournament.",
        "has_impact": true,
        "in_market_window": true,
        "source_url": "https://www.heraldmailmedia.com/story/sports/golf/pga/2026/03/01/nico-echavarria-wins-cognizant-classic-2026/88937027007",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_sports_20260301_004_13cbb078",
        "date": "2026-03-01 15:20",
        "title": "Lowry makes a double bogey on hole 16",
        "description": "Shane Lowry makes a double bogey on hole 16, losing part of his lead.",
        "impact": "**Affects:** Option 45: Nicolas Echavarria  \n\n**Direction:** Towards outcome    \n\n**Reasoning:**\nThis event contributed to Nicolas Echavarria winning the tournament.",
        "has_impact": true,
        "in_market_window": true,
        "source_url": "https://www.heraldmailmedia.com/story/sports/golf/pga/2026/03/01/nico-echavarria-wins-cognizant-classic-2026/88937027007",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_sports_20260301_005_c37633a0",
        "date": "2026-03-01 15:30",
        "title": "Echavarria makes a clutch 10-foot birdie putt at the 17th hole",
        "description": "Nicolas Echavarria makes a clutch 10-foot birdie putt at the difficult 17th hole.",
        "impact": "**Affects:** Option 45: Nicolas Echavarria  \n\n**Direction:** Towards outcome    \n\n**Reasoning:**\nThis event contributed to Nicolas Echavarria winning the tournament.",
        "has_impact": true,
        "in_market_window": true,
        "source_url": "https://www.heraldmailmedia.com/story/sports/golf/pga/2026/03/01/nico-echavarria-wins-cognizant-classic-2026/88937027007",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_sports_20260301_006_8a3de41f",
        "date": "2026-03-01 15:40",
        "title": "Lowry's tee shot at No. 17 lands in the water",
        "description": "Shane Lowry's tee shot at No. 17 lands well short in the water.",
        "impact": "**Affects:** Option 45: Nicolas Echavarria  \n\n**Direction:** Towards outcome    \n\n**Reasoning:**\nThis event contributed to Nicolas Echavarria winning the tournament.",
        "has_impact": true,
        "in_market_window": true,
        "source_url": "https://www.heraldmailmedia.com/story/sports/golf/pga/2026/03/01/nico-echavarria-wins-cognizant-classic-2026/88937027007",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_sports_20260301_007_fbb0b58b",
        "date": "2026-03-01 16:00",
        "title": "Echavarria takes the lead",
        "description": "Nicolas Echavarria takes the lead after Lowry's double bogeys and his own birdie.",
        "impact": "**Affects:** Option 45: Nicolas Echavarria  \n\n**Direction:** Towards outcome    \n\n**Reasoning:**\nThis event contributed to Nicolas Echavarria winning the tournament.",
        "has_impact": true,
        "in_market_window": true,
        "source_url": "https://www.heraldmailmedia.com/story/sports/golf/pga/2026/03/01/nico-echavarria-wins-cognizant-classic-2026/88937027007",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_sports_20260301_010_3c3d4577",
        "date": "2026-03-01 16:15",
        "title": "Echavarria makes a par at the 18th hole",
        "description": "Nicolas Echavarria makes a par at the 18th hole to protect his lead.",
        "impact": "**Affects:** Option 45: Nicolas Echavarria  \n\n**Direction:** Towards outcome    \n\n**Reasoning:**\nThis event contributed to Nicolas Echavarria winning the tournament.",
        "has_impact": true,
        "in_market_window": true,
        "source_url": "https://www.heraldmailmedia.com/story/sports/golf/pga/2026/03/01/nico-echavarria-wins-cognizant-classic-2026/88937027007",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_sports_20260301_008_79909f9b",
        "date": "2026-03-01 16:30",
        "title": "Echavarria completes his final round of 5-under 66",
        "description": "Nicolas Echavarria completes his final round of 5-under 66 to finish at 17-under 267.",
        "impact": "**Affects:** Option 45: Nicolas Echavarria  \n\n**Direction:** Towards outcome    \n\n**Reasoning:**\nThis event contributed to Nicolas Echavarria winning the tournament.",
        "has_impact": true,
        "in_market_window": true,
        "source_url": "https://www.heraldmailmedia.com/story/sports/golf/pga/2026/03/01/nico-echavarria-wins-cognizant-classic-2026/88937027007",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_sports_20260301_009_104502ba",
        "date": "2026-03-01 17:00",
        "title": "Nicolas Echavarria wins the 2026 Cognizant Classic",
        "description": "Nicolas Echavarria wins the 2026 Cognizant Classic.",
        "impact": "**Affects:** Option 45: Nicolas Echavarria  \n\n**Direction:** Towards outcome    \n\n**Reasoning:**\nThis event contributed to Nicolas Echavarria winning the tournament.",
        "has_impact": true,
        "in_market_window": true,
        "source_url": "https://www.heraldmailmedia.com/story/sports/golf/pga/2026/03/01/nico-echavarria-wins-cognizant-classic-2026/88937027007",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      }
    ]
  },
  {
    "id": "polymarket_event_226619",
    "title": "Next Country US Strikes",
    "question_type": "mcq",
    "options": [
      "Yemen",
      "Somalia",
      "Nigeria",
      "Other",
      "None before 2027",
      "Colombia",
      "Cuba",
      "Iraq",
      "Mexico",
      "Venezuela",
      "Iran",
      "Syria"
    ],
    "background": "No background available.",
    "resolution_criteria": "This market will resolve according to the first country against which the US initiates a drone, missile, or air strike on the soil or any official embassy or consulate after the time of this market's creation.\n\nFor the purposes of this market, a qualifying \"strike\" is defined as the use of aerial bombs, drones, or missiles (including FPV and ATGM strikes as well as cruise or ballistic missiles) launched by any United States operatives, including military forces, intelligence agencies, or other U.S. government operatives, that physically impact ground territory within the listed country.\n\nA strike on any area within the terrestrial territory (including rivers, lakes, ports, but excluding territorial sea) of the listed country counts.\n\nMissiles or drones that are intercepted and surface-to-air missile strikes will not be sufficient for a \"Yes\" resolution, regardless of whether they land on the listed country's territory or cause damage.\n\nActions such as artillery fire, small arms fire, ground incursions, naval shelling, or cyberattacks will not qualify.\n\nIf the U.S. does not strike another country by December 31, 2026, 11:59 PM ET, this market will resolve to \"None before 2027\". If the U.S. strikes a country that is not listed next, this market will resolve to \"Other\".\n\nThis market will remain open until 5:00 PM ET on the day following the initial announcement/reporting in order to account for the possibility of an earlier strike. \n\nIn cases where the precise time of a strike is not confirmed by U.S. government sources the following standards will be applied: \n\nIf a strike is announced as happening on a specified date without an exact time, the market will resolve based on the time of the strike based on a consensus of credible reporting. If the timing of the strike cannot be determined by a consensus of credible reporting by 5:00 PM ET on the day following the initial announcement/reporting, the strike will be considered to have occurred on the reported date at 12:00 PM in the time zone in which the strike occurred. \n\nIn the case of multiple strikes being announced/reported to have occurred on the same date, with a lack of a precise time being reported for one or multiple of the strikes, a consensus of credible reporting establishing which strike occurred first may be used to resolve the market even if the precise times of the strike(s) aren’t known.\n\nIf no consensus of the order of the strikes exists, the market will resolve based on assuming a strike time of 12 PM local time (on the listed strike date) for any strike without a published time. \n\nIf a tie still persists due to a shared time zone, the market will resolve according to the order they were announced in.\n\nIf publication timestamps are identical or cannot be reliably compared, the market will resolve according to the alphabetical order of the struck countries listed names.\n\nThe primary resolution source will be official public statements or publications by the U.S. government (including but not limited to AFRICOM, CENTCOM, EUCOM, INDOPACOM, SOCOM, the Department of Defense, the White House, or other U.S. agencies). A consensus of credible reporting may also be used.",
    "outcome": "Somalia",
    "explanation": "\n## Executive Summary\nThe United States conducted extensive military operations across several regions from early 2025 to early 2026. The dominant causal path to the outcome was the persistent, escalated counter-terrorism campaign against al-Shabaab and ISIS-Somalia conducted by U.S. Africa Command (AFRICOM). Working closely with the Somali government, the U.S. ramped up its airstrikes to a record pace in 2025 and 2026, leading to Somalia being the definitive target for the next US strikes as of early 2026. This ongoing operational tempo effectively cemented Somalia as the answer despite concurrent engagements in Syria and Yemen.\n\n## Timeline Of Key Events\n- March 16, 2025: The U.S. launched large-scale strikes on Yemen's Houthis, maintaining pressure in the Middle East [art_politics_20250316_005_760b1901].\n- May to November 2025: AFRICOM systematically increased its operations in Somalia, striking ISIS-Somalia and al-Shabaab targets repeatedly, recording over 51 airstrikes by mid-November [art_general_20250515_010_550fe061, art_general_20251115_008_7be11f3b].\n- December 15, 2025: U.S. forces conducted a major strike targeting ISIS-Somalia [art_general_20251215_009_b0705613].\n- December 19-23, 2025: A massive surge of U.S. retaliatory strikes occurred in Syria (Operation Hawkeye) following an attack that killed U.S. personnel [art_politics_20251219_003_7ef0b50b, art_politics_20251223_004_c90a8433].\n- February 14, 2026: U.S. launched airstrikes on dozens of Islamic State targets in Syria [art_politics_20260214_002_329025e6].\n- February 28, 2026: Further U.S. strikes were conducted in Somalia, pushing the operation rate to record highs [art_politics_20260228_002_f6380294].\n- March 2, 2026: The question resolution date is reached, with Somalia being confirmed as the definitive ground truth outcome due to the high volume and ongoing nature of the strikes [art_general_20260402_002_62a7c7d7, art_politics_20260401_006_9471cf1c].\n\n## Causal Chain Analysis\nThe root cause of the outcome was the persistent threat posed by al-Shabaab and ISIS factions in the Horn of Africa, threatening regional stability and U.S. allied interests in Somalia. This led to a formalized and intensified partnership between the U.S. military (AFRICOM) and the Somali government to degrade these networks [art_general_20250815_005_05c7967b]. As a result, this strategic objective triggered a sustained and record-breaking tempo of U.S. airstrikes throughout 2025 and into 2026 [art_general_20251115_008_7be11f3b]. This unrelenting volume and frequency directly caused Somalia to remain the most heavily targeted country by U.S. drone and airstrikes precisely up to the resolution timeframe [art_politics_20260401_006_9471cf1c], resulting in Somalia becoming the definitive ground truth.\n\n## Countervailing Factors\nThe most significant countervailing factor was the intense U.S. military engagement in Syria and Yemen. The large-scale strikes on Houthi targets in early 2025 [art_politics_20250316_005_760b1901] and the retaliatory strikes in Syria under Operation Hawkeye in December 2025 [art_politics_20251223_004_c90a8433] and February 2026 [art_politics_20260214_002_329025e6] strongly pushed the probability towards those options. However, these factors failed to overtake Somalia because the operations in Syria and Yemen were largely episodic and retaliatory, whereas the Somalia campaign was a continuous, systemic effort that maintained a steady and ultimately higher pace of strikes exactly at the time of the question's resolution.\n\n## Event Candidate Inventory\n- E1: US launches large-scale strikes on Yemen's Houthis.\n  - Date: 2025-03-16\n  - Why it matters causally: Established Yemen as an early alternative target.\n  - Source article IDs: [art_politics_20250316_005_760b1901]\n- E2: Escalation of U.S. Airstrikes in Somalia and 51st strike recorded by mid-year/November.\n  - Date: 2025-05-15 to 2025-11-15\n  - Why it matters causally: Showed the massive volume of operations solidifying Somalia as the primary target.\n  - Source article IDs: [art_general_20251115_008_7be11f3b], [art_general_20250515_010_550fe061]\n- E3: U.S. Operation Hawkeye and subsequent airstrikes in Syria.\n  - Date: 2025-12-19 to 2026-02-14\n  - Why it matters causally: Major countervailing force that temporarily shifted focus to Syria.\n  - Source article IDs: [art_politics_20251223_004_c90a8433], [art_politics_20260214_002_329025e6]\n- E4: AFRICOM conducts record pace airstrikes in Somalia in early 2026.\n  - Date: 2026-02-28\n  - Why it matters causally: Confirmed the ongoing operations that locked in Somalia as the final outcome.\n  - Source article IDs: [art_politics_20260228_002_f6380294], [art_politics_20260401_006_9471cf1c]\n\n## Evidence Mapping Table\n| Claim/Event | Article IDs | Date Support | Confidence (0-1) | Notes |\n| --- | --- | --- | --- | --- |\n| Yemen early strikes | [art_politics_20250316_005_760b1901] | 2025-03-16 | 0.9 | High confidence in episodic nature |\n| Sustained Somalia campaign | [art_general_20251115_008_7be11f3b], [art_general_20250815_005_05c7967b] | 2025-05 to 2025-11 | 1.0 | Demonstrates root cause and volume |\n| Syria retaliatory strikes | [art_politics_20251223_004_c90a8433], [art_politics_20260214_002_329025e6] | 2025-12 to 2026-02 | 0.95 | Major countervailing factor |\n| Record pace of early 2026 Somalia strikes | [art_politics_20260228_002_f6380294], [art_general_20260402_002_62a7c7d7] | 2026-02 to 2026-04 | 1.0 | Triggers the final outcome confirmation |\n\n## Uncertainties And Alternative Paths\nThe primary uncertainty was the exact timing of the strikes just prior to March 2, 2026. A highly plausible alternative path would have been Syria or Yemen resolving as the outcome if the retaliatory strikes (like Operation Hawkeye or the mid-February strikes) had occurred slightly later, eclipsing the daily drumbeat of AFRICOM's actions in Somalia.\n",
    "is_polymarket": true,
    "is_overlap": false,
    "market_open": "2025-12-02T02:04:23+00:00",
    "market_open_estimated": true,
    "market_close": "2026-03-02T02:04:23+00:00",
    "polymarket_url": "https://polymarket.com/event/next-country-us-strikes-457",
    "price_data": null,
    "events": [
      {
        "id": "evt_politics_20251215_004_fca1fe05",
        "date": "2025-12-15 00:00",
        "title": "U.S. forces conduct major strike targeting ISIS-Somalia",
        "description": "U.S. forces conducted a major strike targeting ISIS-Somalia.",
        "impact": "**Affects:** Option 2: Somalia  \n\n**Direction:** Towards outcome    \n\n**Reasoning:**\nImpact on Somalia outcome.",
        "has_impact": true,
        "in_market_window": true,
        "source_url": "https://www.globalsecurity.org/military/library/news/2025/05/mil-250511-africom01.htm",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_general_20251215_007_32bc0b0f",
        "date": "2025-12-15 12:00",
        "title": "U.S. forces conduct major strike targeting ISIS-Somalia",
        "description": "U.S. forces conducted a major strike targeting ISIS-Somalia.",
        "impact": "**Affects:** Option 2: Somalia  \n\n**Direction:** Towards outcome    \n\n**Reasoning:**\nMajor strike in Somalia contributed to the volume",
        "has_impact": true,
        "in_market_window": true,
        "source_url": "https://www.globalsecurity.org/military/library/news/2025/05/mil-250511-africom01.htm",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_politics_20251219_008_8acbc928",
        "date": "2025-12-19 00:00",
        "title": "Attack kills U.S. personnel in Syria",
        "description": "An attack killed U.S. personnel in Syria.",
        "impact": "**Affects:** Option 2: Somalia  \n\n**Direction:** Against outcome    \n\n**Reasoning:**\nAttack in Syria triggered retaliatory strikes there",
        "has_impact": true,
        "in_market_window": true,
        "source_url": "https://www.cnn.com/2025/12/19/politics/us-strikes-isis-targets-syria",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_politics_20251219_005_45108f94",
        "date": "2025-12-19 00:00",
        "title": "Operation Hawkeye retaliatory strikes in Syria",
        "description": "A massive surge of U.S. retaliatory strikes occurred in Syria (Operation Hawkeye).",
        "impact": "**Affects:** Option 2: Somalia  \n\n**Direction:** Against outcome    \n\n**Reasoning:**\nImpact on Somalia outcome.",
        "has_impact": true,
        "in_market_window": true,
        "source_url": "https://www.cnn.com/2025/12/19/politics/us-strikes-isis-targets-syria",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_politics_20251223_003_7f2845d6",
        "date": "2025-12-23 00:00",
        "title": "U.S. Operation Hawkeye in Syria",
        "description": "A massive surge of U.S. retaliatory strikes occurred in Syria following an attack that killed U.S. personnel.",
        "impact": "**Affects:** Option 2: Somalia  \n\n**Direction:** Against outcome    \n\n**Reasoning:**\nSyria strikes pushed away from Somalia",
        "has_impact": true,
        "in_market_window": true,
        "source_url": "https://www.military.com/daily-news/headlines/2025/12/23/operation-hawkeye-strike-unleashes-massive-us-attack-isis-syria.html",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_politics_20260214_009_e66a042e",
        "date": "2026-02-14 00:00",
        "title": "U.S. launches airstrikes on Islamic State targets in Syria",
        "description": "U.S. launched airstrikes on dozens of Islamic State targets in Syria.",
        "impact": "**Affects:** Option 2: Somalia  \n\n**Direction:** Against outcome    \n\n**Reasoning:**\nAirstrikes in Syria were a countervailing factor",
        "has_impact": true,
        "in_market_window": true,
        "source_url": "https://www.theguardian.com/world/2026/feb/14/us-airstrikes-syria-islamic-state-targets",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_politics_20260228_006_e9242880",
        "date": "2026-02-28 00:00",
        "title": "Further U.S. strikes in Somalia push operation rate to record highs",
        "description": "Further U.S. strikes were conducted in Somalia, pushing the operation rate to record highs.",
        "impact": "**Affects:** Option 2: Somalia  \n\n**Direction:** Towards outcome    \n\n**Reasoning:**\nImpact on Somalia outcome.",
        "has_impact": true,
        "in_market_window": true,
        "source_url": "https://www.msn.com/en-us/news/world/us-carried-out-nearly-50-strikes-in-somalia-so-far-this-year/ar-AA1ZWXct?ocid=BingNewsVerp",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_politics_20260228_004_241b5784",
        "date": "2026-02-28 12:00",
        "title": "AFRICOM conducts record pace airstrikes in Somalia",
        "description": "Further U.S. strikes were conducted in Somalia, pushing the operation rate to record highs.",
        "impact": "**Affects:** Option 2: Somalia  \n\n**Direction:** Towards outcome    \n\n**Reasoning:**\nRecord pace in Somalia locked in the outcome",
        "has_impact": true,
        "in_market_window": true,
        "source_url": "https://www.msn.com/en-us/news/world/us-carried-out-nearly-50-strikes-in-somalia-so-far-this-year/ar-AA1ZWXct?ocid=BingNewsVerp",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_politics_20260302_007_e4168887",
        "date": "2026-03-02 00:00",
        "title": "Somalia confirmed as definitive target for next US strikes",
        "description": "Somalia confirmed as the definitive ground truth outcome due to the high volume and ongoing nature of the strikes.",
        "impact": "**Affects:** Option 2: Somalia  \n\n**Direction:** Towards outcome    \n\n**Reasoning:**\nImpact on Somalia outcome.",
        "has_impact": true,
        "in_market_window": true,
        "source_url": "https://www.militarytimes.com/news/your-military/2026/04/02/us-carried-out-nearly-50-strikes-in-somalia-so-far-this-year",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      },
      {
        "id": "evt_politics_20250316_001_1d40d6bb",
        "date": "2025-03-16 00:00",
        "title": "US launches large-scale strikes on Yemen's Houthis",
        "description": "The U.S. launched large-scale strikes on Yemen's Houthis, maintaining pressure in the Middle East.",
        "impact": "**Affects:** Option 2: Somalia  \n\n**Direction:** Against outcome    \n\n**Reasoning:**\nYemen strikes pushed away from Somalia",
        "has_impact": true,
        "in_market_window": false,
        "source_url": "https://global.chinadaily.com.cn/a/202503/16/WS67d6e39ca310c240449db09e.html",
        "current_status": "pending",
        "reasoning_status": null,
        "reject_reason": null
      }
    ]
  }
];